//! Code generator for producing Rust parser code (scannerless)
//!
//! Generates:
//! - Work enum (auto-named variants)
//! - ParseResult enum
//! - Parser struct with trampoline loop
//! - Character-level matching functions

use crate::ir::{CharClass, Combinator};
use crate::CompiledGrammar;

/// Code generator
pub struct CodeGenerator<'a> {
    grammar: &'a CompiledGrammar,
    output: String,
    indent: usize,
}

impl<'a> CodeGenerator<'a> {
    pub fn new(grammar: &'a CompiledGrammar) -> Self {
        Self {
            grammar,
            output: String::new(),
            indent: 0,
        }
    }

    /// Generate the complete parser code
    pub fn generate(mut self) -> String {
        self.emit_header();
        self.emit_span();
        self.emit_parse_error();
        self.emit_parse_result_enum();
        self.emit_work_enum();
        self.emit_parser();
        self.output
    }

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    fn emit_header(&mut self) {
        self.line("//! Auto-generated parser - DO NOT EDIT");
        self.line("//!");
        self.line("//! Generated by trampoline-parser (scannerless)");
        self.blank();
        self.line("#![allow(dead_code)]");
        self.line("#![allow(unused_variables)]");
        self.line("#![allow(non_camel_case_types)]");
        self.line("#![allow(clippy::collapsible_match)]");
        self.line("#![allow(clippy::should_implement_trait)]");
        self.blank();

        // Emit user imports
        for import in &self.grammar.ast_config.imports {
            self.line(&format!("use {};", import));
        }
        if !self.grammar.ast_config.imports.is_empty() {
            self.blank();
        }
    }

    fn emit_span(&mut self) {
        if !self.grammar.ast_config.generate_span {
            return;
        }
        self.line("/// Source location span");
        self.line("#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]");
        self.line("pub struct Span {");
        self.indent += 1;
        self.line("pub start: usize,");
        self.line("pub end: usize,");
        self.line("pub line: u32,");
        self.line("pub column: u32,");
        self.indent -= 1;
        self.line("}");
        self.blank();
    }

    fn emit_parse_error(&mut self) {
        if !self.grammar.ast_config.generate_parse_error {
            return;
        }
        self.line("/// Parse error");
        self.line("#[derive(Debug, Clone)]");
        self.line("pub struct ParseError {");
        self.indent += 1;
        self.line("pub message: String,");
        self.line("pub span: Span,");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("impl std::fmt::Display for ParseError {");
        self.indent += 1;
        self.line("fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {");
        self.indent += 1;
        self.line("write!(f, \"{} at {}..{}\", self.message, self.span.start, self.span.end)");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("impl std::error::Error for ParseError {}");
        self.blank();
    }

    fn emit_parse_result_enum(&mut self) {
        if !self.grammar.ast_config.generate_parse_result {
            return;
        }

        let string_type = self
            .grammar
            .ast_config
            .string_type
            .as_deref()
            .unwrap_or("String");

        self.line("/// Parse result value");
        self.line("#[derive(Debug, Clone)]");
        self.line("pub enum ParseResult {");
        self.indent += 1;
        self.line("/// No value (for skipped items)");
        self.line("None,");
        self.line("/// Captured text");
        self.line(&format!("Text({}, Span),", string_type));
        self.line("/// List of results");
        self.line("List(Vec<ParseResult>),");

        // Emit custom variants
        for variant in &self.grammar.ast_config.result_variants {
            self.line(&format!("{}({}),", variant.name, variant.rust_type));
        }

        self.indent -= 1;
        self.line("}");
        self.blank();

        // Emit helper methods
        self.line("impl ParseResult {");
        self.indent += 1;
        self.line("pub fn span(&self) -> Span {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        self.line("ParseResult::None => Span::default(),");
        self.line("ParseResult::Text(_, span) => *span,");
        self.line("ParseResult::List(items) => {");
        self.indent += 1;
        self.line("if items.is_empty() { return Span::default(); }");
        self.line("let first_span = items.first().map(|i| i.span()).unwrap_or_default();");
        self.line("let last_span = items.last().map(|i| i.span()).unwrap_or_default();");
        self.line("Span { start: first_span.start, end: last_span.end, line: first_span.line, column: first_span.column }");
        self.indent -= 1;
        self.line("}");
        for variant in &self.grammar.ast_config.result_variants {
            if let Some(ref span_expr) = variant.span_expr {
                self.line(&format!(
                    "ParseResult::{}(v) => {},",
                    variant.name,
                    span_expr.replace('_', "v")
                ));
            } else {
                self.line(&format!(
                    "ParseResult::{}(_) => Span::default(),",
                    variant.name
                ));
            }
        }
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
    }

    fn emit_work_enum(&mut self) {
        self.line("/// Work items for the trampoline");
        self.line("#[derive(Debug)]");
        self.line("enum Work {");
        self.indent += 1;

        // Generate work variants for each rule
        for rule in &self.grammar.rules {
            let prefix = to_pascal_case(&rule.name);
            self.emit_work_variants(&prefix, &rule.combinator);
        }

        self.indent -= 1;
        self.line("}");
        self.blank();
    }

    fn emit_work_variants(&mut self, prefix: &str, comb: &Combinator) {
        match comb {
            Combinator::Rule(_) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
            }
            Combinator::Sequence(items) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
                for i in 1..items.len() {
                    self.line(&format!("{}_Seq_Step{} {{ result_base: usize }},", prefix, i));
                }
                self.line(&format!(
                    "{}_Seq_Complete {{ result_base: usize, count: usize }},",
                    prefix
                ));
                // Recurse into children
                for (i, item) in items.iter().enumerate() {
                    let child_prefix = format!("{}_Seq{}", prefix, i);
                    self.emit_work_variants(&child_prefix, item);
                }
            }
            Combinator::Choice(items) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
                for i in 0..items.len() {
                    self.line(&format!(
                        "{}_Choice{}_Try {{ result_base: usize, checkpoint: usize }},",
                        prefix, i
                    ));
                }
                // Recurse into children
                for (i, item) in items.iter().enumerate() {
                    let child_prefix = format!("{}_Choice{}", prefix, i);
                    self.emit_work_variants(&child_prefix, item);
                }
            }
            Combinator::ZeroOrMore(inner) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
                self.line(&format!(
                    "{}_Loop {{ result_base: usize, checkpoint: usize }},",
                    prefix
                ));
                self.line(&format!("{}_Complete {{ result_base: usize }},", prefix));
                let child_prefix = format!("{}_Item", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::OneOrMore(inner) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
                self.line(&format!(
                    "{}_Loop {{ result_base: usize, checkpoint: usize, count: usize }},",
                    prefix
                ));
                self.line(&format!("{}_Complete {{ result_base: usize }},", prefix));
                let child_prefix = format!("{}_Item", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::Optional(inner) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
                self.line(&format!(
                    "{}_Check {{ result_base: usize, checkpoint: usize }},",
                    prefix
                ));
                let child_prefix = format!("{}_Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::Literal(_) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
            }
            Combinator::Char(_) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
            }
            Combinator::CharClass(_) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
            }
            Combinator::CharRange(_, _) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
            }
            Combinator::AnyChar => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
            }
            Combinator::Capture(inner) => {
                self.line(&format!(
                    "{}_Start {{ result_base: usize }},",
                    prefix
                ));
                self.line(&format!("{}_Complete {{ result_base: usize, start_pos: usize, start_line: u32, start_column: u32 }},", prefix));
                let child_prefix = format!("{}_Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::NotFollowedBy(inner) => {
                self.line(&format!(
                    "{}_Start {{ result_base: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}_Check {{ result_base: usize, checkpoint: usize }},",
                    prefix
                ));
                let child_prefix = format!("{}_Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::FollowedBy(inner) => {
                self.line(&format!(
                    "{}_Start {{ result_base: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}_Check {{ result_base: usize, checkpoint: usize }},",
                    prefix
                ));
                let child_prefix = format!("{}_Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::Skip(inner) => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
                self.line(&format!("{}_Complete {{ result_base: usize }},", prefix));
                let child_prefix = format!("{}_Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::SeparatedBy { item, separator, .. } => {
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
                self.line(&format!(
                    "{}_Sep {{ result_base: usize, checkpoint: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}_Item {{ result_base: usize, checkpoint: usize }},",
                    prefix
                ));
                self.line(&format!("{}_Complete {{ result_base: usize }},", prefix));
                let item_prefix = format!("{}_ItemRule", prefix);
                self.emit_work_variants(&item_prefix, item);
                let sep_prefix = format!("{}_SepRule", prefix);
                self.emit_work_variants(&sep_prefix, separator);
            }
            Combinator::Pratt(_) => {
                // Pratt parsing is complex - emit basic variants
                self.line(&format!("{}_Start {{ result_base: usize }},", prefix));
                // TODO: full Pratt support
            }
            Combinator::Mapped { inner, .. } => {
                self.emit_work_variants(prefix, inner);
            }
        }
    }

    fn emit_parser(&mut self) {
        let string_type = self
            .grammar
            .ast_config
            .string_type
            .as_deref()
            .unwrap_or("String");

        let has_string_dict = self.grammar.ast_config.string_dict_type.is_some();
        let string_dict_type = self
            .grammar
            .ast_config
            .string_dict_type
            .as_deref()
            .unwrap_or("StringDict");

        self.line("/// Scannerless parser");
        self.line("pub struct Parser<'a> {");
        self.indent += 1;
        self.line("input: &'a str,");
        self.line("pos: usize,");
        self.line("line: u32,");
        self.line("column: u32,");
        self.line("work_stack: Vec<Work>,");
        self.line("result_stack: Vec<ParseResult>,");
        self.line("last_error: Option<ParseError>,");
        if has_string_dict {
            self.line(&format!("string_dict: &'a mut {},", string_dict_type));
        }
        self.indent -= 1;
        self.line("}");
        self.blank();

        self.line("impl<'a> Parser<'a> {");
        self.indent += 1;

        // Constructor
        if has_string_dict {
            self.line(&format!(
                "pub fn new(input: &'a str, string_dict: &'a mut {}) -> Self {{",
                string_dict_type
            ));
        } else {
            self.line("pub fn new(input: &'a str) -> Self {");
        }
        self.indent += 1;
        self.line("Self {");
        self.indent += 1;
        self.line("input,");
        self.line("pos: 0,");
        self.line("line: 1,");
        self.line("column: 1,");
        self.line("work_stack: Vec::new(),");
        self.line("result_stack: Vec::new(),");
        self.line("last_error: None,");
        if has_string_dict {
            self.line("string_dict,");
        }
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Parse entry point for first rule
        if let Some(first_rule) = self.grammar.rules.first() {
            let prefix = to_pascal_case(&first_rule.name);
            self.line("/// Parse the input");
            self.line("pub fn parse(&mut self) -> Result<ParseResult, ParseError> {");
            self.indent += 1;
            self.line("let result_base = self.result_stack.len();");
            self.line(&format!(
                "self.work_stack.push(Work::{}_Start {{ result_base }});",
                prefix
            ));
            self.line("self.run()?;");
            self.line("self.result_stack.pop().ok_or_else(|| ParseError {");
            self.indent += 1;
            self.line("message: \"No result\".to_string(),");
            self.line("span: Span { start: 0, end: self.pos, line: self.line, column: self.column },");
            self.indent -= 1;
            self.line("})");
            self.indent -= 1;
            self.line("}");
            self.blank();
        }

        // Helper methods
        self.emit_helper_methods(string_type);

        // Trampoline loop
        self.emit_trampoline_loop();

        self.indent -= 1;
        self.line("}");
    }

    fn emit_helper_methods(&mut self, string_type: &str) {
        // Current char
        self.line("fn current_char(&self) -> Option<char> {");
        self.indent += 1;
        self.line("self.input[self.pos..].chars().next()");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Advance by one character and track line/column
        self.line("fn advance(&mut self) {");
        self.indent += 1;
        self.line("if let Some(c) = self.current_char() {");
        self.indent += 1;
        self.line("self.pos += c.len_utf8();");
        self.line("if c == '\\n' {");
        self.indent += 1;
        self.line("self.line += 1;");
        self.line("self.column = 1;");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("self.column += 1;");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Match literal with line tracking
        self.line("fn match_literal(&mut self, lit: &str) -> bool {");
        self.indent += 1;
        self.line("if self.input[self.pos..].starts_with(lit) {");
        self.indent += 1;
        self.line("for c in lit.chars() {");
        self.indent += 1;
        self.line("self.pos += c.len_utf8();");
        self.line("if c == '\\n' {");
        self.indent += 1;
        self.line("self.line += 1;");
        self.line("self.column = 1;");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("self.column += 1;");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("true");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("false");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Match char class with line tracking
        self.line("fn match_char_class(&mut self, class: fn(char) -> bool) -> Option<char> {");
        self.indent += 1;
        self.line("if let Some(c) = self.current_char() {");
        self.indent += 1;
        self.line("if class(c) {");
        self.indent += 1;
        self.line("self.pos += c.len_utf8();");
        self.line("if c == '\\n' {");
        self.indent += 1;
        self.line("self.line += 1;");
        self.line("self.column = 1;");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("self.column += 1;");
        self.indent -= 1;
        self.line("}");
        self.line("return Some(c);");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("None");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Create span at current position
        self.line("fn make_span(&self, start: usize) -> Span {");
        self.indent += 1;
        self.line("Span {");
        self.indent += 1;
        self.line("start,");
        self.line("end: self.pos,");
        self.line("line: self.line,");
        self.line("column: self.column,");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Create text result
        self.line(&format!(
            "fn text_result(&self, start: usize, end: usize) -> {} {{",
            string_type
        ));
        self.indent += 1;
        if string_type == "String" {
            self.line("self.input[start..end].to_string()");
        } else {
            // For custom string types like JsString, assume From<&str>
            self.line(&format!(
                "{}::from(&self.input[start..end])",
                string_type
            ));
        }
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Make error
        self.line("fn make_error(&self, msg: &str) -> ParseError {");
        self.indent += 1;
        self.line("ParseError {");
        self.indent += 1;
        self.line("message: msg.to_string(),");
        self.line("span: Span { start: self.pos, end: self.pos, line: self.line, column: self.column },");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
    }

    fn emit_trampoline_loop(&mut self) {
        self.line("fn run(&mut self) -> Result<(), ParseError> {");
        self.indent += 1;
        self.line("while let Some(work) = self.work_stack.pop() {");
        self.indent += 1;
        self.line("self.execute(work)?;");
        self.indent -= 1;
        self.line("}");
        self.line("if let Some(err) = self.last_error.take() {");
        self.indent += 1;
        self.line("return Err(err);");
        self.indent -= 1;
        self.line("}");
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Execute method
        self.line("fn execute(&mut self, work: Work) -> Result<(), ParseError> {");
        self.indent += 1;
        self.line("match work {");
        self.indent += 1;

        // Generate handlers for each rule
        for rule in &self.grammar.rules {
            let prefix = to_pascal_case(&rule.name);
            self.emit_work_handlers(&prefix, &rule.combinator);
        }

        self.indent -= 1;
        self.line("}");
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_work_handlers(&mut self, prefix: &str, comb: &Combinator) {
        match comb {
            Combinator::Rule(name) => {
                let target_prefix = to_pascal_case(name);
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    target_prefix
                ));
                self.indent -= 1;
                self.line("}");
            }
            Combinator::Literal(lit) => {
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!("if !self.match_literal({:?}) {{", lit));
                self.indent += 1;
                self.line(&format!(
                    "self.last_error = Some(self.make_error(\"expected '{}'\"));",
                    lit.escape_default()
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::Char(c) => {
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!(
                    "if self.current_char() == Some({:?}) {{",
                    c
                ));
                self.indent += 1;
                self.line("self.advance();");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line(&format!(
                    "self.last_error = Some(self.make_error(\"expected '{}'\"));",
                    c.escape_default()
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::CharClass(class) => {
                let check_fn = char_class_check(*class);
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!(
                    "if self.match_char_class({}).is_none() {{",
                    check_fn
                ));
                self.indent += 1;
                self.line(&format!(
                    "self.last_error = Some(self.make_error(\"expected {}\"));",
                    char_class_name(*class)
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::CharRange(from, to) => {
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("if let Some(c) = self.current_char() {");
                self.indent += 1;
                self.line(&format!("if c >= {:?} && c <= {:?} {{", from, to));
                self.indent += 1;
                self.line("self.advance();");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line(&format!(
                    "self.last_error = Some(self.make_error(\"expected char in range '{}'..='{}'\"));",
                    from.escape_default(),
                    to.escape_default()
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.last_error = Some(self.make_error(\"unexpected end of input\"));");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::AnyChar => {
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("if self.current_char().is_some() {");
                self.indent += 1;
                self.line("self.advance();");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.last_error = Some(self.make_error(\"unexpected end of input\"));");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::Sequence(items) => {
                // Start: push completion, then first item
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Seq_Complete {{ result_base, count: {} }});",
                    prefix,
                    items.len()
                ));
                // Push items in reverse order
                for i in (1..items.len()).rev() {
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Seq_Step{} {{ result_base }});",
                        prefix, i
                    ));
                }
                // Emit first item inline
                let first_prefix = format!("{}_Seq0", prefix);
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    first_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Step handlers
                for i in 1..items.len() {
                    self.line(&format!(
                        "Work::{}_Seq_Step{} {{ result_base }} => {{",
                        prefix, i
                    ));
                    self.indent += 1;
                    self.line("if self.last_error.is_some() { return Ok(()); }");
                    let step_prefix = format!("{}_Seq{}", prefix, i);
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Start {{ result_base }});",
                        step_prefix
                    ));
                    self.indent -= 1;
                    self.line("}");
                }

                // Complete handler
                self.line(&format!(
                    "Work::{}_Seq_Complete {{ result_base, count }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("let results: Vec<_> = self.result_stack.drain(result_base..).collect();");
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.result_stack.truncate(result_base);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse into children
                for (i, item) in items.iter().enumerate() {
                    let child_prefix = format!("{}_Seq{}", prefix, i);
                    self.emit_work_handlers(&child_prefix, item);
                }
            }
            Combinator::Choice(items) => {
                // Start: try first alternative
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Choice0_Try {{ result_base, checkpoint }});",
                    prefix
                ));
                let first_prefix = format!("{}_Choice0", prefix);
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    first_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Try handlers
                for i in 0..items.len() {
                    self.line(&format!(
                        "Work::{}_Choice{}_Try {{ result_base, checkpoint }} => {{",
                        prefix, i
                    ));
                    self.indent += 1;
                    self.line("if self.last_error.is_some() {");
                    self.indent += 1;
                    self.line("self.last_error = None;");
                    self.line("self.pos = checkpoint;");
                    self.line("self.result_stack.truncate(result_base);");
                    if i + 1 < items.len() {
                        // Try next alternative
                        self.line(&format!(
                            "self.work_stack.push(Work::{}_Choice{}_Try {{ result_base, checkpoint }});",
                            prefix,
                            i + 1
                        ));
                        let next_prefix = format!("{}_Choice{}", prefix, i + 1);
                        self.line(&format!(
                            "self.work_stack.push(Work::{}_Start {{ result_base }});",
                            next_prefix
                        ));
                    } else {
                        // No more alternatives
                        self.line("self.last_error = Some(self.make_error(\"no alternative matched\"));");
                    }
                    self.indent -= 1;
                    self.line("}");
                    // If no error, result is already on stack
                    self.indent -= 1;
                    self.line("}");
                }

                // Recurse into children
                for (i, item) in items.iter().enumerate() {
                    let child_prefix = format!("{}_Choice{}", prefix, i);
                    self.emit_work_handlers(&child_prefix, item);
                }
            }
            Combinator::ZeroOrMore(inner) => {
                let item_prefix = format!("{}_Item", prefix);

                // Start
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Loop {{ result_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Loop
                self.line(&format!(
                    "Work::{}_Loop {{ result_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                // Pop the failed item result if any
                self.line("if self.result_stack.len() > result_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Complete {{ result_base }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Loop {{ result_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Complete
                self.line(&format!(
                    "Work::{}_Complete {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let results: Vec<_> = self.result_stack.drain(result_base..).collect();");
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&item_prefix, inner);
            }
            Combinator::OneOrMore(inner) => {
                let item_prefix = format!("{}_Item", prefix);

                // Start - must match at least one
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Loop {{ result_base, checkpoint, count: 0 }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Loop
                self.line(&format!(
                    "Work::{}_Loop {{ result_base, checkpoint, count }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("if count == 0 {");
                self.indent += 1;
                self.line("// First item failed - propagate error");
                self.line("return Ok(());");
                self.indent -= 1;
                self.line("}");
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                self.line("if self.result_stack.len() > result_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Complete {{ result_base }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Loop {{ result_base, checkpoint, count: count + 1 }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Complete
                self.line(&format!(
                    "Work::{}_Complete {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let results: Vec<_> = self.result_stack.drain(result_base..).collect();");
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&item_prefix, inner);
            }
            Combinator::Optional(inner) => {
                let inner_prefix = format!("{}_Inner", prefix);

                // Start
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Check {{ result_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Check
                self.line(&format!(
                    "Work::{}_Check {{ result_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                self.line("self.result_stack.truncate(result_base);");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                // If no error, result is already on stack
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::Capture(inner) => {
                let inner_prefix = format!("{}_Inner", prefix);

                // Start
                self.line(&format!(
                    "Work::{}_Start {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let start_pos = self.pos;");
                self.line("let start_line = self.line;");
                self.line("let start_column = self.column;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Complete {{ result_base, start_pos, start_line, start_column }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Complete
                self.line(&format!(
                    "Work::{}_Complete {{ result_base, start_pos, start_line, start_column }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("// Remove inner results, replace with captured text");
                self.line("self.result_stack.truncate(result_base);");
                self.line("let text = self.text_result(start_pos, self.pos);");
                self.line("let span = Span { start: start_pos, end: self.pos, line: start_line, column: start_column };");
                self.line("self.result_stack.push(ParseResult::Text(text, span));");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::NotFollowedBy(inner) => {
                let inner_prefix = format!("{}_Inner", prefix);

                // Start
                self.line(&format!(
                    "Work::{}_Start {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Check {{ result_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Check - success if inner failed
                self.line(&format!(
                    "Work::{}_Check {{ result_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("self.pos = checkpoint;");
                self.line("self.result_stack.truncate(result_base);");
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("// Inner failed - that's what we want");
                self.line("self.last_error = None;");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("// Inner succeeded - that's a failure for not_followed_by");
                self.line("self.last_error = Some(self.make_error(\"unexpected match\"));");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::FollowedBy(inner) => {
                let inner_prefix = format!("{}_Inner", prefix);

                // Start
                self.line(&format!(
                    "Work::{}_Start {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Check {{ result_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Check - restore position but keep success/failure
                self.line(&format!(
                    "Work::{}_Check {{ result_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("self.pos = checkpoint;");
                self.line("self.result_stack.truncate(result_base);");
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::Skip(inner) => {
                let inner_prefix = format!("{}_Inner", prefix);

                // Start
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Complete {{ result_base }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Complete - discard result
                self.line(&format!(
                    "Work::{}_Complete {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("self.result_stack.truncate(result_base);");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::SeparatedBy { item, separator, trailing } => {
                let item_prefix = format!("{}_ItemRule", prefix);
                let sep_prefix = format!("{}_SepRule", prefix);

                // Start - try first item
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Sep {{ result_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Sep - after item, try separator
                self.line(&format!(
                    "Work::{}_Sep {{ result_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("// First item failed - return empty list");
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                self.line("self.result_stack.truncate(result_base);");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Complete {{ result_base }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Item {{ result_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start {{ result_base }});",
                    sep_prefix
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Item - after separator, try next item
                self.line(&format!(
                    "Work::{}_Item {{ result_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("// Separator failed - done");
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                // Pop the failed separator result
                self.line("if self.result_stack.len() > result_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Complete {{ result_base }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                // Separator matched, try next item
                if *trailing {
                    self.line("// Allow trailing separator");
                    self.line("let checkpoint = self.pos;");
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Sep {{ result_base, checkpoint }});",
                        prefix
                    ));
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Start {{ result_base }});",
                        item_prefix
                    ));
                } else {
                    self.line("let checkpoint = self.pos;");
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Sep {{ result_base, checkpoint }});",
                        prefix
                    ));
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Start {{ result_base }});",
                        item_prefix
                    ));
                }
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Complete
                self.line(&format!(
                    "Work::{}_Complete {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("// Filter out separator results (None values between items)");
                self.line("let results: Vec<_> = self.result_stack.drain(result_base..)");
                self.indent += 1;
                self.line(".enumerate()");
                self.line(".filter(|(i, _)| i % 2 == 0)  // Keep items, skip separators");
                self.line(".map(|(_, r)| r)");
                self.line(".collect();");
                self.indent -= 1;
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&item_prefix, item);
                self.emit_work_handlers(&sep_prefix, separator);
            }
            Combinator::Pratt(_) => {
                // Simplified Pratt - just start
                self.line(&format!("Work::{}_Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("// TODO: Pratt parsing not yet implemented for scannerless");
                self.line("self.last_error = Some(self.make_error(\"Pratt parsing not implemented\"));");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::Mapped { inner, .. } => {
                // For now, just delegate to inner
                self.emit_work_handlers(prefix, inner);
            }
        }
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

fn char_class_check(class: CharClass) -> &'static str {
    match class {
        CharClass::Digit => "|c: char| c.is_ascii_digit()",
        CharClass::HexDigit => "|c: char| c.is_ascii_hexdigit()",
        CharClass::Alpha => "|c: char| c.is_ascii_alphabetic()",
        CharClass::AlphaNumeric => "|c: char| c.is_ascii_alphanumeric()",
        CharClass::Whitespace => "|c: char| c.is_ascii_whitespace()",
        CharClass::IdentStart => "|c: char| c.is_ascii_alphabetic() || c == '_' || c == '$'",
        CharClass::IdentCont => "|c: char| c.is_ascii_alphanumeric() || c == '_' || c == '$'",
    }
}

fn char_class_name(class: CharClass) -> &'static str {
    match class {
        CharClass::Digit => "digit",
        CharClass::HexDigit => "hex digit",
        CharClass::Alpha => "letter",
        CharClass::AlphaNumeric => "alphanumeric",
        CharClass::Whitespace => "whitespace",
        CharClass::IdentStart => "identifier start",
        CharClass::IdentCont => "identifier character",
    }
}

#[cfg(test)]
mod tests {
    use crate::Grammar;

    #[test]
    fn test_simple_grammar_generates() {
        let grammar = Grammar::new()
            .rule("digit", |r| r.digit())
            .build();

        let code = grammar.generate();
        assert!(code.contains("pub struct Parser"));
        assert!(code.contains("enum Work"));
    }
}
