//! Code generator for producing Rust parser code (scannerless)
//!
//! Generates:
//! - Work enum (auto-named variants)
//! - ParseResult enum
//! - Parser struct with trampoline loop
//! - Character-level matching functions

use crate::ir::{CharClass, Combinator};
use crate::CompiledGrammar;

/// Code generator
pub struct CodeGenerator<'a> {
    grammar: &'a CompiledGrammar,
    output: String,
    indent: usize,
}

impl<'a> CodeGenerator<'a> {
    pub fn new(grammar: &'a CompiledGrammar) -> Self {
        Self {
            grammar,
            output: String::new(),
            indent: 0,
        }
    }

    /// Generate the complete parser code
    pub fn generate(mut self) -> String {
        self.emit_header();
        self.emit_span();
        self.emit_parse_error();
        self.emit_parse_result_enum();
        self.emit_helpers();
        self.emit_work_enum();
        self.emit_parser();
        self.output
    }

    fn emit_helpers(&mut self) {
        for helper in &self.grammar.ast_config.helper_code {
            self.output.push_str(helper);
            self.blank();
        }
    }

    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    fn emit_header(&mut self) {
        self.line("// Auto-generated parser - DO NOT EDIT");
        self.line("//");
        self.line("// Generated by trampoline-parser (scannerless)");
        self.blank();

        // Emit user imports
        for import in &self.grammar.ast_config.imports {
            self.line(&format!("use {};", import));
        }
        if !self.grammar.ast_config.imports.is_empty() {
            self.blank();
        }
    }

    fn emit_span(&mut self) {
        if !self.grammar.ast_config.generate_span {
            return;
        }
        self.line("/// Source location span");
        self.line("#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]");
        self.line("pub struct Span {");
        self.indent += 1;
        self.line("pub start: usize,");
        self.line("pub end: usize,");
        self.line("pub line: u32,");
        self.line("pub column: u32,");
        self.indent -= 1;
        self.line("}");
        self.blank();
    }

    fn emit_parse_error(&mut self) {
        if !self.grammar.ast_config.generate_parse_error {
            return;
        }
        self.line("/// Parse error");
        self.line("#[derive(Debug, Clone)]");
        self.line("pub struct ParseError {");
        self.indent += 1;
        self.line("pub message: String,");
        self.line("pub span: Span,");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("impl ParseError {");
        self.indent += 1;
        self.line("pub fn new(message: String, line: u32, column: u32) -> Self {");
        self.indent += 1;
        self.line("Self { message, span: Span { start: 0, end: 0, line, column } }");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("impl std::fmt::Display for ParseError {");
        self.indent += 1;
        self.line("fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {");
        self.indent += 1;
        self.line("write!(f, \"{} at {}..{}\", self.message, self.span.start, self.span.end)");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("impl std::error::Error for ParseError {}");
        self.blank();
    }

    fn emit_parse_result_enum(&mut self) {
        if !self.grammar.ast_config.generate_parse_result {
            return;
        }

        let string_type = self
            .grammar
            .ast_config
            .string_type
            .as_deref()
            .unwrap_or("String");

        self.line("/// Parse result value");
        self.line("#[derive(Debug, Clone)]");
        self.line("pub enum ParseResult {");
        self.indent += 1;
        self.line("/// No value (for skipped items)");
        self.line("None,");
        self.line("/// Captured text");
        self.line(&format!("Text({}, Span),", string_type));
        self.line("/// List of results");
        self.line("List(Vec<ParseResult>),");

        // Emit custom variants
        for variant in &self.grammar.ast_config.result_variants {
            self.line(&format!("{}({}),", variant.name, variant.rust_type));
        }

        self.indent -= 1;
        self.line("}");
        self.blank();

        // Emit helper methods
        self.line("impl ParseResult {");
        self.indent += 1;
        self.line("pub fn span(&self) -> Span {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        self.line("ParseResult::None => Span::default(),");
        self.line("ParseResult::Text(_, span) => *span,");
        self.line("ParseResult::List(items) => {");
        self.indent += 1;
        self.line("if items.is_empty() { return Span::default(); }");
        self.line("let first_span = items.first().map(|i| i.span()).unwrap_or_default();");
        self.line("let last_span = items.last().map(|i| i.span()).unwrap_or_default();");
        self.line("Span { start: first_span.start, end: last_span.end, line: first_span.line, column: first_span.column }");
        self.indent -= 1;
        self.line("}");
        for variant in &self.grammar.ast_config.result_variants {
            if let Some(ref span_expr) = variant.span_expr {
                self.line(&format!(
                    "ParseResult::{}(v) => {},",
                    variant.name,
                    span_expr.replace('_', "v")
                ));
            } else {
                self.line(&format!(
                    "ParseResult::{}(_) => Span::default(),",
                    variant.name
                ));
            }
        }
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
    }

    fn emit_work_enum(&mut self) {
        self.line("/// Work items for the trampoline");
        self.line("#[derive(Debug)]");
        self.line("enum Work {");
        self.indent += 1;

        // Generate work variants for each rule
        for rule in &self.grammar.rules {
            let prefix = to_pascal_case(&rule.name);
            self.emit_work_variants(&prefix, &rule.combinator);
        }

        self.indent -= 1;
        self.line("}");
        self.blank();
    }

    fn emit_work_variants(&mut self, prefix: &str, comb: &Combinator) {
        match comb {
            Combinator::Rule(_) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
            }
            Combinator::Sequence(items) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
                for i in 1..items.len() {
                    self.line(&format!(
                        "{}SeqStep{} {{ result_base: usize, seq_base: usize }},",
                        prefix, i
                    ));
                }
                self.line(&format!(
                    "{}SeqComplete {{ result_base: usize, seq_base: usize, count: usize }},",
                    prefix
                ));
                // Recurse into children
                for (i, item) in items.iter().enumerate() {
                    let child_prefix = format!("{}Seq{}", prefix, i);
                    self.emit_work_variants(&child_prefix, item);
                }
            }
            Combinator::Choice(items) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
                for i in 0..items.len() {
                    self.line(&format!(
                        "{}Choice{}Try {{ result_base: usize, checkpoint: usize, stack_base: usize }},",
                        prefix, i
                    ));
                }
                // Recurse into children
                for (i, item) in items.iter().enumerate() {
                    let child_prefix = format!("{}Choice{}", prefix, i);
                    self.emit_work_variants(&child_prefix, item);
                }
            }
            Combinator::ZeroOrMore(inner) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
                self.line(&format!(
                    "{}Loop {{ result_base: usize, loop_base: usize, checkpoint: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}Complete {{ result_base: usize, loop_base: usize }},",
                    prefix
                ));
                let child_prefix = format!("{}Item", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::OneOrMore(inner) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
                self.line(&format!(
                    "{}Loop {{ result_base: usize, loop_base: usize, checkpoint: usize, count: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}Complete {{ result_base: usize, loop_base: usize }},",
                    prefix
                ));
                let child_prefix = format!("{}Item", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::Optional(inner) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
                self.line(&format!(
                    "{}Check {{ result_base: usize, opt_base: usize, checkpoint: usize }},",
                    prefix
                ));
                let child_prefix = format!("{}Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::Literal(_) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
            }
            Combinator::Char(_) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
            }
            Combinator::CharClass(_) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
            }
            Combinator::CharRange(_, _) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
            }
            Combinator::AnyChar => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
            }
            Combinator::Capture(inner) => {
                self.line(&format!(
                    "{}Start {{ result_base: usize }},",
                    prefix
                ));
                self.line(&format!("{}Complete {{ result_base: usize, capture_base: usize, start_pos: usize, start_line: u32, start_column: u32 }},", prefix));
                let child_prefix = format!("{}Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::NotFollowedBy(inner) => {
                self.line(&format!(
                    "{}Start {{ result_base: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}Check {{ result_base: usize, nfb_base: usize, checkpoint: usize }},",
                    prefix
                ));
                let child_prefix = format!("{}Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::FollowedBy(inner) => {
                self.line(&format!(
                    "{}Start {{ result_base: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}Check {{ result_base: usize, fb_base: usize, checkpoint: usize }},",
                    prefix
                ));
                let child_prefix = format!("{}Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::Skip(inner) => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
                self.line(&format!(
                    "{}Complete {{ result_base: usize, skip_base: usize }},",
                    prefix
                ));
                let child_prefix = format!("{}Inner", prefix);
                self.emit_work_variants(&child_prefix, inner);
            }
            Combinator::SeparatedBy { item, separator, .. } => {
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
                self.line(&format!(
                    "{}Sep {{ result_base: usize, list_base: usize, checkpoint: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}Item {{ result_base: usize, list_base: usize, checkpoint: usize }},",
                    prefix
                ));
                self.line(&format!("{}Complete {{ result_base: usize, list_base: usize }},", prefix));
                let item_prefix = format!("{}ItemRule", prefix);
                self.emit_work_variants(&item_prefix, item);
                let sep_prefix = format!("{}SepRule", prefix);
                self.emit_work_variants(&sep_prefix, separator);
            }
            Combinator::Pratt(pratt) => {
                // Pratt parsing work variants
                self.line(&format!("{}Start {{ result_base: usize }},", prefix));
                self.line(&format!("{}ParseOperand {{ result_base: usize, min_prec: u8, start_pos: usize, start_line: u32, start_column: u32 }},", prefix));
                self.line(&format!("{}AfterOperand {{ result_base: usize, min_prec: u8, start_pos: usize, start_line: u32, start_column: u32 }},", prefix));
                self.line(&format!("{}AfterInfix {{ result_base: usize, min_prec: u8, op_idx: usize, start_pos: usize, start_line: u32, start_column: u32 }},", prefix));
                self.line(&format!("{}AfterPrefix {{ result_base: usize, min_prec: u8, op_idx: usize, start_pos: usize, start_line: u32, start_column: u32 }},", prefix));

                // Emit operand parser variants
                if let Some(operand) = pratt.operand.as_ref() {
                    let operand_prefix = format!("{}Operand", prefix);
                    self.emit_work_variants(&operand_prefix, operand);
                }
            }
            Combinator::Mapped { inner, .. } => {
                let inner_prefix = format!("{}Inner", prefix);
                self.emit_work_variants(&inner_prefix, inner);
                // Add our own Start and Map variants
                self.line(&format!(
                    "{}Start {{ result_base: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}Map {{ result_base: usize, map_base: usize, start_pos: usize, start_line: u32, start_column: u32 }},",
                    prefix
                ));
            }
        }
    }

    fn emit_parser(&mut self) {
        let string_type = self
            .grammar
            .ast_config
            .string_type
            .as_deref()
            .unwrap_or("String");

        let has_string_dict = self.grammar.ast_config.string_dict_type.is_some();
        let string_dict_type = self
            .grammar
            .ast_config
            .string_dict_type
            .as_deref()
            .unwrap_or("StringDict");

        self.line("/// Scannerless parser");
        self.line("pub struct Parser<'a> {");
        self.indent += 1;
        self.line("input: &'a str,");
        self.line("pos: usize,");
        self.line("line: u32,");
        self.line("column: u32,");
        self.line("work_stack: Vec<Work>,");
        self.line("result_stack: Vec<ParseResult>,");
        self.line("last_error: Option<ParseError>,");
        if has_string_dict {
            self.line(&format!("string_dict: &'a mut {},", string_dict_type));
        }
        self.indent -= 1;
        self.line("}");
        self.blank();

        self.line("impl<'a> Parser<'a> {");
        self.indent += 1;

        // Constructor
        if has_string_dict {
            self.line(&format!(
                "pub fn new(input: &'a str, string_dict: &'a mut {}) -> Self {{",
                string_dict_type
            ));
        } else {
            self.line("pub fn new(input: &'a str) -> Self {");
        }
        self.indent += 1;
        self.line("Self {");
        self.indent += 1;
        self.line("input,");
        self.line("pos: 0,");
        self.line("line: 1,");
        self.line("column: 1,");
        self.line("work_stack: Vec::new(),");
        self.line("result_stack: Vec::new(),");
        self.line("last_error: None,");
        if has_string_dict {
            self.line("string_dict,");
        }
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Parse entry point for first rule
        if let Some(first_rule) = self.grammar.rules.first() {
            let prefix = to_pascal_case(&first_rule.name);
            self.line("/// Parse the input");
            self.line("pub fn parse(&mut self) -> Result<ParseResult, ParseError> {");
            self.indent += 1;
            self.line("let result_base = self.result_stack.len();");
            self.line(&format!(
                "self.work_stack.push(Work::{}Start {{ result_base }});",
                prefix
            ));
            self.line("self.run()?;");
            self.line("self.result_stack.pop().ok_or_else(|| ParseError {");
            self.indent += 1;
            self.line("message: \"No result\".to_string(),");
            self.line("span: Span { start: 0, end: self.pos, line: self.line, column: self.column },");
            self.indent -= 1;
            self.line("})");
            self.indent -= 1;
            self.line("}");
            self.blank();
        }

        // Helper methods
        self.emit_helper_methods(string_type);

        // Trampoline loop
        self.emit_trampoline_loop();

        self.indent -= 1;
        self.line("}");
    }

    fn emit_helper_methods(&mut self, string_type: &str) {
        // Current char
        self.line("fn current_char(&self) -> Option<char> {");
        self.indent += 1;
        self.line("self.input[self.pos..].chars().next()");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Advance by one character and track line/column
        self.line("fn advance(&mut self) {");
        self.indent += 1;
        self.line("if let Some(c) = self.current_char() {");
        self.indent += 1;
        self.line("self.pos += c.len_utf8();");
        self.line("if c == '\\n' {");
        self.indent += 1;
        self.line("self.line += 1;");
        self.line("self.column = 1;");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("self.column += 1;");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Match literal with line tracking
        self.line("fn match_literal(&mut self, lit: &str) -> bool {");
        self.indent += 1;
        self.line("if self.input[self.pos..].starts_with(lit) {");
        self.indent += 1;
        self.line("for c in lit.chars() {");
        self.indent += 1;
        self.line("self.pos += c.len_utf8();");
        self.line("if c == '\\n' {");
        self.indent += 1;
        self.line("self.line += 1;");
        self.line("self.column = 1;");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("self.column += 1;");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("true");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("false");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Match char class with line tracking
        self.line("fn match_char_class(&mut self, class: fn(char) -> bool) -> Option<char> {");
        self.indent += 1;
        self.line("if let Some(c) = self.current_char() {");
        self.indent += 1;
        self.line("if class(c) {");
        self.indent += 1;
        self.line("self.pos += c.len_utf8();");
        self.line("if c == '\\n' {");
        self.indent += 1;
        self.line("self.line += 1;");
        self.line("self.column = 1;");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("self.column += 1;");
        self.indent -= 1;
        self.line("}");
        self.line("return Some(c);");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("None");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Create span at current position
        self.line("fn make_span(&self, start: usize) -> Span {");
        self.indent += 1;
        self.line("Span {");
        self.indent += 1;
        self.line("start,");
        self.line("end: self.pos,");
        self.line("line: self.line,");
        self.line("column: self.column,");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Create text result
        self.line(&format!(
            "fn text_result(&self, start: usize, end: usize) -> {} {{",
            string_type
        ));
        self.indent += 1;
        if string_type == "String" {
            self.line("self.input[start..end].to_string()");
        } else {
            // For custom string types like JsString, assume From<&str>
            self.line(&format!(
                "{}::from(&self.input[start..end])",
                string_type
            ));
        }
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Make error
        self.line("fn make_error(&self, msg: &str) -> ParseError {");
        self.indent += 1;
        self.line("ParseError {");
        self.indent += 1;
        self.line("message: msg.to_string(),");
        self.line("span: Span { start: self.pos, end: self.pos, line: self.line, column: self.column },");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Try to consume a literal (for Pratt parsing)
        self.line("fn try_consume(&mut self, s: &str) -> bool {");
        self.indent += 1;
        self.line("if self.input[self.pos..].starts_with(s) {");
        self.indent += 1;
        self.line("for c in s.chars() {");
        self.indent += 1;
        self.line("if c == '\\n' {");
        self.indent += 1;
        self.line("self.line += 1;");
        self.line("self.column = 1;");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("self.column += 1;");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("self.pos += s.len();");
        self.line("true");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("false");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Skip whitespace (for Pratt parsing)
        self.line("fn skip_ws(&mut self) {");
        self.indent += 1;
        self.line("while self.pos < self.input.len() {");
        self.indent += 1;
        self.line("let c = self.input[self.pos..].chars().next().unwrap_or('\\0');");
        self.line("if c == ' ' || c == '\\t' || c == '\\r' {");
        self.indent += 1;
        self.line("self.pos += 1;");
        self.line("self.column += 1;");
        self.indent -= 1;
        self.line("} else if c == '\\n' {");
        self.indent += 1;
        self.line("self.pos += 1;");
        self.line("self.line += 1;");
        self.line("self.column = 1;");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("break;");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
    }

    fn emit_trampoline_loop(&mut self) {
        self.line("fn run(&mut self) -> Result<(), ParseError> {");
        self.indent += 1;
        self.line("while let Some(work) = self.work_stack.pop() {");
        self.indent += 1;
        self.line("self.execute(work)?;");
        self.indent -= 1;
        self.line("}");
        self.line("if let Some(err) = self.last_error.take() {");
        self.indent += 1;
        self.line("return Err(err);");
        self.indent -= 1;
        self.line("}");
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Execute method
        self.line("fn execute(&mut self, work: Work) -> Result<(), ParseError> {");
        self.indent += 1;
        self.line("match work {");
        self.indent += 1;

        // Generate handlers for each rule
        for rule in &self.grammar.rules {
            let prefix = to_pascal_case(&rule.name);
            self.emit_work_handlers(&prefix, &rule.combinator);
        }

        self.indent -= 1;
        self.line("}");
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_work_handlers(&mut self, prefix: &str, comb: &Combinator) {
        match comb {
            Combinator::Rule(name) => {
                let target_prefix = to_pascal_case(name);
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    target_prefix
                ));
                self.indent -= 1;
                self.line("}");
            }
            Combinator::Literal(lit) => {
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!("if !self.match_literal({:?}) {{", lit));
                self.indent += 1;
                self.line(&format!(
                    "self.last_error = Some(self.make_error(\"expected '{}'\"));",
                    lit.escape_default()
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::Char(c) => {
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!(
                    "if self.current_char() == Some({:?}) {{",
                    c
                ));
                self.indent += 1;
                self.line("self.advance();");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line(&format!(
                    "self.last_error = Some(self.make_error(\"expected '{}'\"));",
                    c.escape_default()
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::CharClass(class) => {
                let check_fn = char_class_check(*class);
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line(&format!(
                    "if self.match_char_class({}).is_none() {{",
                    check_fn
                ));
                self.indent += 1;
                self.line(&format!(
                    "self.last_error = Some(self.make_error(\"expected {}\"));",
                    char_class_name(*class)
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::CharRange(from, to) => {
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("if let Some(c) = self.current_char() {");
                self.indent += 1;
                self.line(&format!("if c >= {:?} && c <= {:?} {{", from, to));
                self.indent += 1;
                self.line("self.advance();");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line(&format!(
                    "self.last_error = Some(self.make_error(\"expected char in range '{}'..='{}'\"));",
                    from.escape_default(),
                    to.escape_default()
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.last_error = Some(self.make_error(\"unexpected end of input\"));");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::AnyChar => {
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("if self.current_char().is_some() {");
                self.indent += 1;
                self.line("self.advance();");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.last_error = Some(self.make_error(\"unexpected end of input\"));");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::Sequence(items) => {
                // Start: capture seq_base, push completion, then first item
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let seq_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}SeqComplete {{ result_base, seq_base, count: {} }});",
                    prefix,
                    items.len()
                ));
                // Push items in reverse order
                for i in (1..items.len()).rev() {
                    self.line(&format!(
                        "self.work_stack.push(Work::{}SeqStep{} {{ result_base, seq_base }});",
                        prefix, i
                    ));
                }
                // Emit first item inline
                let first_prefix = format!("{}Seq0", prefix);
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    first_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Step handlers
                for i in 1..items.len() {
                    self.line(&format!(
                        "Work::{}SeqStep{} {{ result_base, seq_base }} => {{",
                        prefix, i
                    ));
                    self.indent += 1;
                    self.line("if self.last_error.is_some() { return Ok(()); }");
                    let step_prefix = format!("{}Seq{}", prefix, i);
                    self.line(&format!(
                        "self.work_stack.push(Work::{}Start {{ result_base }});",
                        step_prefix
                    ));
                    self.indent -= 1;
                    self.line("}");
                }

                // Complete handler - use seq_base for drain/truncate
                self.line(&format!(
                    "Work::{}SeqComplete {{ result_base, seq_base, count }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("let results: Vec<_> = self.result_stack.drain(seq_base..).collect();");
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("self.result_stack.truncate(seq_base);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse into children
                for (i, item) in items.iter().enumerate() {
                    let child_prefix = format!("{}Seq{}", prefix, i);
                    self.emit_work_handlers(&child_prefix, item);
                }
            }
            Combinator::Choice(items) => {
                // Start: capture stack base and try first alternative
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line("let stack_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Choice0Try {{ result_base, checkpoint, stack_base }});",
                    prefix
                ));
                let first_prefix = format!("{}Choice0", prefix);
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    first_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Try handlers - use stack_base for truncation, not result_base
                for i in 0..items.len() {
                    self.line(&format!(
                        "Work::{}Choice{}Try {{ result_base, checkpoint, stack_base }} => {{",
                        prefix, i
                    ));
                    self.indent += 1;
                    self.line("if self.last_error.is_some() {");
                    self.indent += 1;
                    self.line("self.last_error = None;");
                    self.line("self.pos = checkpoint;");
                    self.line("self.result_stack.truncate(stack_base);");
                    if i + 1 < items.len() {
                        // Try next alternative
                        self.line(&format!(
                            "self.work_stack.push(Work::{}Choice{}Try {{ result_base, checkpoint, stack_base }});",
                            prefix,
                            i + 1
                        ));
                        let next_prefix = format!("{}Choice{}", prefix, i + 1);
                        self.line(&format!(
                            "self.work_stack.push(Work::{}Start {{ result_base }});",
                            next_prefix
                        ));
                    } else {
                        // No more alternatives
                        self.line("self.last_error = Some(self.make_error(\"no alternative matched\"));");
                    }
                    self.indent -= 1;
                    self.line("}");
                    // If no error, result is already on stack
                    self.indent -= 1;
                    self.line("}");
                }

                // Recurse into children
                for (i, item) in items.iter().enumerate() {
                    let child_prefix = format!("{}Choice{}", prefix, i);
                    self.emit_work_handlers(&child_prefix, item);
                }
            }
            Combinator::ZeroOrMore(inner) => {
                let item_prefix = format!("{}Item", prefix);

                // Start - capture loop_base to track where this loop's results start
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line("let loop_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Loop {{ result_base, loop_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Loop - use loop_base for result tracking
                self.line(&format!(
                    "Work::{}Loop {{ result_base, loop_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                // Pop the failed item result if any (use loop_base, not result_base)
                self.line("if self.result_stack.len() > loop_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Complete {{ result_base, loop_base }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Loop {{ result_base, loop_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Complete - drain only this loop's results using loop_base
                self.line(&format!(
                    "Work::{}Complete {{ result_base, loop_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let results: Vec<_> = self.result_stack.drain(loop_base..).collect();");
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&item_prefix, inner);
            }
            Combinator::OneOrMore(inner) => {
                let item_prefix = format!("{}Item", prefix);

                // Start - must match at least one, capture loop_base
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line("let loop_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Loop {{ result_base, loop_base, checkpoint, count: 0 }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Loop - use loop_base for result tracking
                self.line(&format!(
                    "Work::{}Loop {{ result_base, loop_base, checkpoint, count }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("if count == 0 {");
                self.indent += 1;
                self.line("// First item failed - propagate error");
                self.line("return Ok(());");
                self.indent -= 1;
                self.line("}");
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                self.line("if self.result_stack.len() > loop_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Complete {{ result_base, loop_base }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Loop {{ result_base, loop_base, checkpoint, count: count + 1 }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Complete - drain only this loop's results using loop_base
                self.line(&format!(
                    "Work::{}Complete {{ result_base, loop_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let results: Vec<_> = self.result_stack.drain(loop_base..).collect();");
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&item_prefix, inner);
            }
            Combinator::Optional(inner) => {
                let inner_prefix = format!("{}Inner", prefix);

                // Start - capture opt_base to track where this optional's results start
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line("let opt_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Check {{ result_base, opt_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Check - use opt_base for truncation, not result_base
                self.line(&format!(
                    "Work::{}Check {{ result_base, opt_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                self.line("self.result_stack.truncate(opt_base);");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                // If no error, result is already on stack
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::Capture(inner) => {
                let inner_prefix = format!("{}Inner", prefix);

                // Start - capture base for truncation
                self.line(&format!(
                    "Work::{}Start {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let start_pos = self.pos;");
                self.line("let start_line = self.line;");
                self.line("let start_column = self.column;");
                self.line("let capture_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Complete {{ result_base, capture_base, start_pos, start_line, start_column }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Complete - use capture_base for truncation
                self.line(&format!(
                    "Work::{}Complete {{ result_base, capture_base, start_pos, start_line, start_column }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("// Remove inner results, replace with captured text");
                self.line("self.result_stack.truncate(capture_base);");
                self.line("let text = self.text_result(start_pos, self.pos);");
                self.line("let span = Span { start: start_pos, end: self.pos, line: start_line, column: start_column };");
                self.line("self.result_stack.push(ParseResult::Text(text, span));");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::NotFollowedBy(inner) => {
                let inner_prefix = format!("{}Inner", prefix);

                // Start - capture nfb_base for truncation
                self.line(&format!(
                    "Work::{}Start {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line("let nfb_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Check {{ result_base, nfb_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Check - success if inner failed, use nfb_base for truncation
                self.line(&format!(
                    "Work::{}Check {{ result_base: _, nfb_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("self.pos = checkpoint;");
                self.line("self.result_stack.truncate(nfb_base);");
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("// Inner failed - that's what we want");
                self.line("self.last_error = None;");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("// Inner succeeded - that's a failure for not_followed_by");
                self.line("self.last_error = Some(self.make_error(\"unexpected match\"));");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::FollowedBy(inner) => {
                let inner_prefix = format!("{}Inner", prefix);

                // Start - capture fb_base for truncation
                self.line(&format!(
                    "Work::{}Start {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line("let fb_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Check {{ result_base, fb_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Check - restore position but keep success/failure, use fb_base for truncation
                self.line(&format!(
                    "Work::{}Check {{ result_base: _, fb_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("self.pos = checkpoint;");
                self.line("self.result_stack.truncate(fb_base);");
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::Skip(inner) => {
                let inner_prefix = format!("{}Inner", prefix);

                // Start - capture current stack length as skip_base
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let skip_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Complete {{ result_base, skip_base }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Complete - discard inner results only, not previous sequence elements
                self.line(&format!(
                    "Work::{}Complete {{ result_base, skip_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("self.result_stack.truncate(skip_base);");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&inner_prefix, inner);
            }
            Combinator::SeparatedBy { item, separator, trailing } => {
                let item_prefix = format!("{}ItemRule", prefix);
                let sep_prefix = format!("{}SepRule", prefix);

                // Start - try first item, capture list_base
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line("let list_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Sep {{ result_base, list_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    item_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Sep - after item, try separator
                self.line(&format!(
                    "Work::{}Sep {{ result_base, list_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("// First item failed - return empty list");
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                self.line("self.result_stack.truncate(list_base);");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Complete {{ result_base, list_base }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("let checkpoint = self.pos;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Item {{ result_base, list_base, checkpoint }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    sep_prefix
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Item - after separator, try next item
                self.line(&format!(
                    "Work::{}Item {{ result_base, list_base, checkpoint }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() {");
                self.indent += 1;
                self.line("// Separator failed - done (no need to pop, failed combinator doesn't push)");
                self.line("self.last_error = None;");
                self.line("self.pos = checkpoint;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Complete {{ result_base, list_base }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                // Separator matched, try next item
                if *trailing {
                    self.line("// Allow trailing separator");
                    self.line("let checkpoint = self.pos;");
                    self.line(&format!(
                        "self.work_stack.push(Work::{}Sep {{ result_base, list_base, checkpoint }});",
                        prefix
                    ));
                    self.line(&format!(
                        "self.work_stack.push(Work::{}Start {{ result_base }});",
                        item_prefix
                    ));
                } else {
                    self.line("let checkpoint = self.pos;");
                    self.line(&format!(
                        "self.work_stack.push(Work::{}Sep {{ result_base, list_base, checkpoint }});",
                        prefix
                    ));
                    self.line(&format!(
                        "self.work_stack.push(Work::{}Start {{ result_base }});",
                        item_prefix
                    ));
                }
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Complete - use list_base for drain
                self.line(&format!(
                    "Work::{}Complete {{ result_base: _, list_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("// Filter out separator results (None values between items)");
                self.line("let results: Vec<_> = self.result_stack.drain(list_base..)");
                self.indent += 1;
                self.line(".enumerate()");
                self.line(".filter(|(i, _)| i % 2 == 0)  // Keep items, skip separators");
                self.line(".map(|(_, r)| r)");
                self.line(".collect();");
                self.indent -= 1;
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.indent -= 1;
                self.line("}");

                // Recurse
                self.emit_work_handlers(&item_prefix, item);
                self.emit_work_handlers(&sep_prefix, separator);
            }
            Combinator::Pratt(pratt) => {
                let operand_prefix = format!("{}Operand", prefix);

                // Start - begin Pratt parsing with min precedence 0
                self.line(&format!("Work::{}Start {{ result_base }} => {{", prefix));
                self.indent += 1;
                self.line("let start_pos = self.pos;");
                self.line("let start_line = self.line;");
                self.line("let start_column = self.column;");
                self.line(&format!(
                    "self.work_stack.push(Work::{}ParseOperand {{ result_base, min_prec: 0, start_pos, start_line, start_column }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("}");

                // ParseOperand - try prefix operators, then parse operand
                self.line(&format!(
                    "Work::{}ParseOperand {{ result_base, min_prec, start_pos, start_line, start_column }} => {{",
                    prefix
                ));
                self.indent += 1;

                // Try each prefix operator
                if !pratt.prefix_ops.is_empty() {
                    self.line("let prefix_checkpoint = self.pos;");
                    self.line("let mut prefix_matched = false;");

                    for (i, prefix_op) in pratt.prefix_ops.iter().enumerate() {
                        let (op_lit, is_keyword) = extract_operator_pattern(prefix_op.pattern.as_ref());
                        if !op_lit.is_empty() {
                            self.line(&format!("if !prefix_matched && self.try_consume(\"{}\") {{", escape_string(&op_lit)));
                            self.indent += 1;

                            // For keyword operators, check that we're not in the middle of an identifier
                            if is_keyword {
                                self.line("// Keyword boundary check: must not be followed by identifier char");
                                self.line("if self.current_char().map_or(true, |c| !(c.is_ascii_alphanumeric() || c == '_' || c == '$')) {");
                                self.indent += 1;
                            }

                            self.line("prefix_matched = true;");
                            self.line("self.skip_ws();");
                            self.line(&format!(
                                "self.work_stack.push(Work::{}AfterPrefix {{ result_base, min_prec, op_idx: {}, start_pos, start_line, start_column }});",
                                prefix, i
                            ));
                            // Use current stack length as result_base to not interfere with outer parsing
                            self.line(&format!(
                                "self.work_stack.push(Work::{}ParseOperand {{ result_base: self.result_stack.len(), min_prec: {}, start_pos: self.pos, start_line: self.line, start_column: self.column }});",
                                prefix, prefix_op.precedence
                            ));

                            if is_keyword {
                                self.indent -= 1;
                                self.line("} else {");
                                self.indent += 1;
                                self.line("// Keyword followed by ident char - restore and try next");
                                self.line("self.pos = prefix_checkpoint;");
                                self.indent -= 1;
                                self.line("}");
                            }

                            self.indent -= 1;
                            self.line("}");
                        }
                    }

                    // No prefix matched - parse operand directly
                    self.line("if !prefix_matched {");
                    self.indent += 1;
                }

                self.line(&format!(
                    "self.work_stack.push(Work::{}AfterOperand {{ result_base, min_prec, start_pos, start_line, start_column }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    operand_prefix
                ));

                if !pratt.prefix_ops.is_empty() {
                    self.indent -= 1;
                    self.line("}");
                }

                self.indent -= 1;
                self.line("}");

                // AfterPrefix - apply prefix operator mapping
                self.line(&format!(
                    "Work::{}AfterPrefix {{ result_base, min_prec, op_idx, start_pos, start_line, start_column }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("let operand = self.result_stack.pop().unwrap_or(ParseResult::None);");
                self.line("let span = Span { start: start_pos, end: self.pos, line: start_line, column: start_column };");
                self.line("match op_idx {");
                self.indent += 1;
                for (i, prefix_op) in pratt.prefix_ops.iter().enumerate() {
                    self.line(&format!("{} => {{", i));
                    self.indent += 1;
                    self.line(&format!("let mapping_fn = {};", prefix_op.mapping));
                    self.line("match mapping_fn(operand, span) {");
                    self.indent += 1;
                    self.line("Ok(mapped) => self.result_stack.push(mapped),");
                    self.line("Err(e) => self.last_error = Some(e),");
                    self.indent -= 1;
                    self.line("}");
                    self.indent -= 1;
                    self.line("}");
                }
                self.line("_ => {}");
                self.indent -= 1;
                self.line("}");
                // Continue with infix loop
                self.line(&format!(
                    "self.work_stack.push(Work::{}AfterOperand {{ result_base, min_prec, start_pos, start_line, start_column }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // AfterOperand - check for infix operators
                self.line(&format!(
                    "Work::{}AfterOperand {{ result_base, min_prec, start_pos, start_line, start_column }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_some() { return Ok(()); }");

                if !pratt.infix_ops.is_empty() {
                    // Try each infix operator (sorted by length for correct matching)
                    let mut sorted_ops: Vec<_> = pratt.infix_ops.iter().enumerate().collect();
                    sorted_ops.sort_by(|a, b| {
                        let (lit_a, _) = extract_operator_pattern(a.1.pattern.as_ref());
                        let (lit_b, _) = extract_operator_pattern(b.1.pattern.as_ref());
                        lit_b.len().cmp(&lit_a.len()) // Longer operators first
                    });

                    // Skip whitespace before checking for infix operators
                    self.line("self.skip_ws();");
                    self.line("let infix_checkpoint = self.pos;");

                    for (_, (i, infix_op)) in sorted_ops.iter().enumerate() {
                        let (op_lit, is_keyword) = extract_operator_pattern(infix_op.pattern.as_ref());
                        if !op_lit.is_empty() {
                            let prec = infix_op.precedence;
                            let next_prec = if infix_op.assoc == crate::Assoc::Right { prec } else { prec + 1 };

                            self.line(&format!("if {} >= min_prec && self.pos == infix_checkpoint && self.try_consume(\"{}\") {{", prec, escape_string(&op_lit)));
                            self.indent += 1;

                            // For keyword operators, check that we're not in the middle of an identifier
                            if is_keyword {
                                self.line("// Keyword boundary check: must not be followed by identifier char");
                                self.line("if self.current_char().map_or(true, |c| !(c.is_ascii_alphanumeric() || c == '_' || c == '$')) {");
                                self.indent += 1;
                            }

                            self.line("self.skip_ws();");
                            self.line(&format!(
                                "self.work_stack.push(Work::{}AfterInfix {{ result_base, min_prec, op_idx: {}, start_pos, start_line, start_column }});",
                                prefix, i
                            ));
                            // Use current stack length as result_base for right operand to preserve left operand
                            self.line(&format!(
                                "self.work_stack.push(Work::{}ParseOperand {{ result_base: self.result_stack.len(), min_prec: {}, start_pos: self.pos, start_line: self.line, start_column: self.column }});",
                                prefix, next_prec
                            ));

                            if is_keyword {
                                self.indent -= 1;
                                self.line("} else {");
                                self.indent += 1;
                                self.line("// Keyword followed by ident char - restore and try next");
                                self.line("self.pos = infix_checkpoint;");
                                self.indent -= 1;
                                self.line("}");
                            }

                            self.indent -= 1;
                            self.line("}");
                        }
                    }
                }
                // No more operators - we're done
                self.indent -= 1;
                self.line("}");

                // AfterInfix - apply infix operator mapping and continue loop
                self.line(&format!(
                    "Work::{}AfterInfix {{ result_base, min_prec, op_idx, start_pos, start_line, start_column }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                self.line("let right = self.result_stack.pop().unwrap_or(ParseResult::None);");
                self.line("let left = self.result_stack.pop().unwrap_or(ParseResult::None);");
                self.line("let span = Span { start: start_pos, end: self.pos, line: start_line, column: start_column };");
                self.line("match op_idx {");
                self.indent += 1;
                for (i, infix_op) in pratt.infix_ops.iter().enumerate() {
                    self.line(&format!("{} => {{", i));
                    self.indent += 1;
                    self.line(&format!("let mapping_fn = {};", infix_op.mapping));
                    self.line("match mapping_fn(left, right, span) {");
                    self.indent += 1;
                    self.line("Ok(mapped) => self.result_stack.push(mapped),");
                    self.line("Err(e) => self.last_error = Some(e),");
                    self.indent -= 1;
                    self.line("}");
                    self.indent -= 1;
                    self.line("}");
                }
                self.line("_ => {}");
                self.indent -= 1;
                self.line("}");
                // Continue infix loop
                self.line(&format!(
                    "self.work_stack.push(Work::{}AfterOperand {{ result_base, min_prec, start_pos, start_line, start_column }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Emit operand parser handlers
                if let Some(operand) = pratt.operand.as_ref() {
                    self.emit_work_handlers(&operand_prefix, operand);
                }
            }
            Combinator::Mapped { inner, mapping } => {
                let inner_prefix = format!("{}Inner", prefix);

                // Start handler - records position, pushes Map completion, then inner Start
                self.line(&format!(
                    "Work::{}Start {{ result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let start_pos = self.pos;");
                self.line("let start_line = self.line;");
                self.line("let start_column = self.column;");
                self.line("let map_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}Map {{ result_base, map_base, start_pos, start_line, start_column }});",
                    prefix
                ));
                self.line(&format!(
                    "self.work_stack.push(Work::{}Start {{ result_base }});",
                    inner_prefix
                ));
                self.indent -= 1;
                self.line("}");

                // Map handler - applies the mapping closure to the result
                self.line(&format!(
                    "Work::{}Map {{ result_base, map_base, start_pos, start_line, start_column }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("if self.last_error.is_none() {");
                self.indent += 1;
                // Collect results from inner into a single result (use map_base, not result_base)
                self.line("let inner_results: Vec<ParseResult> = self.result_stack.drain(map_base..).collect();");
                self.line("let result = if inner_results.len() == 1 {");
                self.indent += 1;
                self.line("inner_results.into_iter().next().unwrap_or(ParseResult::None)");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("ParseResult::List(inner_results)");
                self.indent -= 1;
                self.line("};");
                self.line("let span = Span { start: start_pos, end: self.pos, line: start_line, column: start_column };");
                // Apply the mapping closure
                self.line(&format!("let mapping_fn = {};", mapping));
                self.line("match mapping_fn(result, span) {");
                self.indent += 1;
                self.line("Ok(mapped) => self.result_stack.push(mapped),");
                self.line("Err(e) => self.last_error = Some(e),");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                // Recurse for inner handlers
                self.emit_work_handlers(&inner_prefix, inner);
            }
        }
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().chain(chars).collect(),
            }
        })
        .collect()
}

fn char_class_check(class: CharClass) -> &'static str {
    match class {
        CharClass::Digit => "|c: char| c.is_ascii_digit()",
        CharClass::HexDigit => "|c: char| c.is_ascii_hexdigit()",
        CharClass::Alpha => "|c: char| c.is_ascii_alphabetic()",
        CharClass::AlphaNumeric => "|c: char| c.is_ascii_alphanumeric()",
        CharClass::Whitespace => "|c: char| c.is_ascii_whitespace()",
        CharClass::IdentStart => "|c: char| c.is_ascii_alphabetic() || c == '_' || c == '$'",
        CharClass::IdentCont => "|c: char| c.is_ascii_alphanumeric() || c == '_' || c == '$'",
    }
}

fn char_class_name(class: CharClass) -> &'static str {
    match class {
        CharClass::Digit => "digit",
        CharClass::HexDigit => "hex digit",
        CharClass::Alpha => "letter",
        CharClass::AlphaNumeric => "alphanumeric",
        CharClass::Whitespace => "whitespace",
        CharClass::IdentStart => "identifier start",
        CharClass::IdentCont => "identifier character",
    }
}

fn escape_string(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '\\' => "\\\\".to_string(),
            '"' => "\\\"".to_string(),
            '\n' => "\\n".to_string(),
            '\r' => "\\r".to_string(),
            '\t' => "\\t".to_string(),
            c => c.to_string(),
        })
        .collect()
}

/// Check if a pattern is a keyword pattern (Literal followed by NotFollowedBy(IdentCont))
/// Returns (literal, is_keyword)
fn extract_operator_pattern(pattern: &Combinator) -> (String, bool) {
    match pattern {
        Combinator::Literal(s) => (s.clone(), false),
        Combinator::Sequence(parts) if parts.len() >= 2 => {
            if let Combinator::Literal(s) = &parts[0] {
                // Check if second part is NotFollowedBy(CharClass(IdentCont))
                let is_keyword = matches!(
                    &parts[1],
                    Combinator::NotFollowedBy(inner) if matches!(inner.as_ref(), Combinator::CharClass(CharClass::IdentCont))
                );
                (s.clone(), is_keyword)
            } else {
                (String::new(), false)
            }
        }
        Combinator::Sequence(parts) if parts.len() == 1 => {
            if let Combinator::Literal(s) = &parts[0] {
                (s.clone(), false)
            } else {
                (String::new(), false)
            }
        }
        _ => (String::new(), false),
    }
}

#[cfg(test)]
mod tests {
    use crate::Grammar;

    #[test]
    fn test_simple_grammar_generates() {
        let grammar = Grammar::new()
            .rule("digit", |r| r.digit())
            .build();

        let code = grammar.generate();
        assert!(code.contains("pub struct Parser"));
        assert!(code.contains("enum Work"));
    }
}
