//! Code generator for producing Rust parser code
//!
//! Generates:
//! - Token enum
//! - Lexer struct with state machine
//! - Work enum (auto-named variants)
//! - ParseResult enum
//! - Parser struct with trampoline loop

use crate::ir::{Combinator, RuleDef, SpecialScan, TokenDef, TokenKind};
use crate::CompiledGrammar;

/// Code generator
pub struct CodeGenerator<'a> {
    grammar: &'a CompiledGrammar,
    output: String,
    indent: usize,
}

impl<'a> CodeGenerator<'a> {
    pub fn new(grammar: &'a CompiledGrammar) -> Self {
        Self {
            grammar,
            output: String::new(),
            indent: 0,
        }
    }

    /// Generate the complete parser code
    pub fn generate(mut self) -> String {
        self.emit_header();
        self.emit_token_enum();
        self.emit_lexer();
        self.emit_work_enum();
        self.emit_parse_result_enum();
        self.emit_parser();
        self.output
    }

    fn emit_header(&mut self) {
        self.line("//! Auto-generated parser - DO NOT EDIT");
        self.line("//!");
        self.line("//! Generated by trampoline-parser");
        self.line("");
        self.line("#![allow(dead_code)]");
        self.line("#![allow(unused_variables)]");
        self.line("#![allow(non_camel_case_types)]");
        self.line("");

        // Emit configured imports
        for import in &self.grammar.ast_config.imports {
            self.line(&format!("use {};", import));
        }
        if !self.grammar.ast_config.imports.is_empty() {
            self.line("");
        }
    }

    fn emit_token_enum(&mut self) {
        self.line("/// Token types");
        self.line("#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
        self.line("pub enum TokenKind {");
        self.indent += 1;

        // Emit token variants
        for token in &self.grammar.lexer.tokens {
            self.line(&format!("{},", token.name));
        }

        // Emit keyword variants
        for keyword in &self.grammar.lexer.keywords {
            self.line(&format!("{},", keyword.name));
        }

        // Always include EOF
        self.line("EOF,");

        self.indent -= 1;
        self.line("}");
        self.line("");

        // TokenKind::name() method
        self.line("impl TokenKind {");
        self.indent += 1;
        self.line("pub fn name(&self) -> &'static str {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        for token in &self.grammar.lexer.tokens {
            self.line(&format!("TokenKind::{} => \"{}\",", token.name, token.name));
        }
        for keyword in &self.grammar.lexer.keywords {
            self.line(&format!(
                "TokenKind::{} => \"{}\",",
                keyword.name, keyword.name
            ));
        }
        self.line("TokenKind::EOF => \"EOF\",");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // Token struct - use configured types if specified
        let string_type = self
            .grammar
            .ast_config
            .string_type
            .as_deref()
            .unwrap_or("String");
        let span_type = self
            .grammar
            .ast_config
            .span_type
            .as_deref()
            .unwrap_or("Span");

        self.line("/// A token with its kind, text, and span");
        self.line("#[derive(Debug, Clone)]");
        self.line("pub struct Token {");
        self.indent += 1;
        self.line("pub kind: TokenKind,");
        self.line(&format!("pub text: {},", string_type));
        self.line(&format!("pub span: {},", span_type));
        self.indent -= 1;
        self.line("}");
        self.line("");

        // Span struct - skip if using external span type
        if self.grammar.ast_config.generate_span {
            self.line("/// Source location span");
            self.line("#[derive(Debug, Clone, Copy, Default)]");
            self.line("pub struct Span {");
            self.indent += 1;
            self.line("pub start: usize,");
            self.line("pub end: usize,");
            self.line("pub line: usize,");
            self.line("pub column: usize,");
            self.indent -= 1;
            self.line("}");
            self.line("");

            // Add Span methods when apply_mappings is enabled
            if self.grammar.ast_config.apply_mappings {
                self.line("impl Span {");
                self.indent += 1;

                // merge method - combines two spans into one covering both
                self.line("/// Merge two spans into one covering both");
                self.line("#[allow(dead_code)]");
                self.line("pub fn merge(self, other: Span) -> Span {");
                self.indent += 1;
                self.line("if other.start == 0 && other.end == 0 {");
                self.indent += 1;
                self.line("return self;");
                self.indent -= 1;
                self.line("}");
                self.line("if self.start == 0 && self.end == 0 {");
                self.indent += 1;
                self.line("return other;");
                self.indent -= 1;
                self.line("}");
                self.line("Span {");
                self.indent += 1;
                self.line("start: self.start.min(other.start),");
                self.line("end: self.end.max(other.end),");
                self.line("line: self.line.min(other.line),");
                self.line("column: if self.start <= other.start { self.column } else { other.column },");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");

                self.indent -= 1;
                self.line("}");
                self.line("");
            }
        }
    }

    fn emit_lexer(&mut self) {
        let has_string_dict = self.grammar.ast_config.string_dict_type.is_some();
        let string_dict_type = self
            .grammar
            .ast_config
            .string_dict_type
            .as_deref()
            .unwrap_or("StringDict");

        self.line("/// Lexer state");
        self.line("pub struct Lexer<'a> {");
        self.indent += 1;
        self.line("input: &'a str,");
        self.line("pos: usize,");
        self.line("line: usize,");
        self.line("column: usize,");
        self.line("peeked: Option<Token>,");
        if has_string_dict {
            self.line(&format!("string_dict: &'a mut {},", string_dict_type));
        }
        self.indent -= 1;
        self.line("}");
        self.line("");

        // Lexer impl
        self.line("impl<'a> Lexer<'a> {");
        self.indent += 1;

        // new
        if has_string_dict {
            self.line(&format!(
                "pub fn new(input: &'a str, string_dict: &'a mut {}) -> Self {{",
                string_dict_type
            ));
        } else {
            self.line("pub fn new(input: &'a str) -> Self {");
        }
        self.indent += 1;
        self.line("Self {");
        self.indent += 1;
        self.line("input,");
        self.line("pos: 0,");
        self.line("line: 1,");
        self.line("column: 1,");
        self.line("peeked: None,");
        if has_string_dict {
            self.line("string_dict,");
        }
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // peek
        self.line("pub fn peek(&mut self) -> Result<&Token, ParseError> {");
        self.indent += 1;
        self.line("if self.peeked.is_none() {");
        self.indent += 1;
        self.line("self.peeked = Some(self.next_token()?);");
        self.indent -= 1;
        self.line("}");
        self.line("Ok(self.peeked.as_ref().unwrap())");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // next
        self.line("pub fn next(&mut self) -> Result<Token, ParseError> {");
        self.indent += 1;
        self.line("if let Some(token) = self.peeked.take() {");
        self.indent += 1;
        self.line("return Ok(token);");
        self.indent -= 1;
        self.line("}");
        self.line("self.next_token()");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // checkpoint/restore
        self.line("pub fn checkpoint(&self) -> LexerCheckpoint {");
        self.indent += 1;
        self.line("LexerCheckpoint {");
        self.indent += 1;
        self.line("pos: self.pos,");
        self.line("line: self.line,");
        self.line("column: self.column,");
        self.line("peeked: self.peeked.clone(),");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        self.line("pub fn restore(&mut self, checkpoint: LexerCheckpoint) {");
        self.indent += 1;
        self.line("self.pos = checkpoint.pos;");
        self.line("self.line = checkpoint.line;");
        self.line("self.column = checkpoint.column;");
        self.line("self.peeked = checkpoint.peeked;");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // span
        self.line("pub fn span(&self) -> Span {");
        self.indent += 1;
        self.line("Span {");
        self.indent += 1;
        self.line("start: self.pos,");
        self.line("end: self.pos,");
        self.line("line: self.line,");
        self.line("column: self.column,");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // next_token - the main lexing logic
        self.emit_next_token();

        // skip_whitespace
        self.emit_skip_whitespace();

        self.indent -= 1;
        self.line("}");
        self.line("");

        // LexerCheckpoint
        self.line("#[derive(Debug, Clone)]");
        self.line("pub struct LexerCheckpoint {");
        self.indent += 1;
        self.line("pos: usize,");
        self.line("line: usize,");
        self.line("column: usize,");
        self.line("peeked: Option<Token>,");
        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    /// Generate code to create a token text from a string literal
    fn emit_string_literal(&self, literal: &str) -> String {
        let escaped = literal.replace('\\', "\\\\").replace('"', "\\\"");
        if self.grammar.ast_config.string_dict_type.is_some() {
            let method = self
                .grammar
                .ast_config
                .string_dict_method
                .as_deref()
                .unwrap_or("get_or_insert");
            format!("self.string_dict.{}(\"{}\")", method, escaped)
        } else {
            format!("\"{}\".to_string()", escaped)
        }
    }

    /// Generate code to create a token text from a string slice expression
    /// The slice_expr should be an expression that evaluates to &str (e.g., "&self.input[start..end]")
    fn emit_string_from_slice(&self, slice_expr: &str) -> String {
        if self.grammar.ast_config.string_dict_type.is_some() {
            let method = self
                .grammar
                .ast_config
                .string_dict_method
                .as_deref()
                .unwrap_or("get_or_insert");
            format!("self.string_dict.{}({})", method, slice_expr)
        } else {
            // For .to_string(), the slice_expr is a &str, so we can call to_string() on it
            format!("({}).to_string()", slice_expr)
        }
    }

    /// Generate code for an empty string
    fn emit_empty_string(&self) -> String {
        if self.grammar.ast_config.string_dict_type.is_some() {
            let method = self
                .grammar
                .ast_config
                .string_dict_method
                .as_deref()
                .unwrap_or("get_or_insert");
            format!("self.string_dict.{}(\"\")", method)
        } else {
            "String::new()".to_string()
        }
    }

    fn emit_next_token(&mut self) {
        self.line("fn next_token(&mut self) -> Result<Token, ParseError> {");
        self.indent += 1;

        self.line("self.skip_whitespace();");
        self.line("");
        self.line("let start = self.pos;");
        self.line("let start_line = self.line;");
        self.line("let start_column = self.column;");
        self.line("");
        self.line("if self.pos >= self.input.len() {");
        self.indent += 1;
        self.line("return Ok(Token {");
        self.indent += 1;
        self.line("kind: TokenKind::EOF,");
        let empty_text = self.emit_empty_string();
        self.line(&format!("text: {},", empty_text));
        self.line("span: Span { start, end: start, line: start_line, column: start_column },");
        self.indent -= 1;
        self.line("});");
        self.indent -= 1;
        self.line("}");
        self.line("");

        self.line("let remaining = &self.input[self.pos..];");
        self.line("");

        // Try keywords first (they have priority)
        if !self.grammar.lexer.keywords.is_empty() {
            self.emit_keyword_matching();
        }

        // Try literal tokens (sorted by length, longest first)
        self.emit_literal_token_matching();

        // Try pattern-based tokens
        self.emit_pattern_token_matching();

        // Fallback error
        self.line("");
        self.line("Err(ParseError {");
        self.indent += 1;
        self.line("span: Span { start, end: start + 1, line: start_line, column: start_column },");
        self.line("expected: vec![],");
        self.line("found: format!(\"unexpected character '{}'\", remaining.chars().next().unwrap_or('?')),");
        self.indent -= 1;
        self.line("})");

        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn emit_keyword_matching(&mut self) {
        self.line("// Check keywords");
        for kw in &self.grammar.lexer.keywords {
            self.line(&format!(
                "if remaining.starts_with(\"{}\") && !remaining.get({}..{}).map(|s| s.starts_with(|c: char| c.is_alphanumeric() || c == '_')).unwrap_or(false) {{",
                kw.literal,
                kw.literal.len(),
                kw.literal.len() + 1
            ));
            self.indent += 1;
            self.line(&format!("let len = {};", kw.literal.len()));
            self.line("self.pos += len;");
            self.line("self.column += len;");
            self.line("return Ok(Token {");
            self.indent += 1;
            self.line(&format!("kind: TokenKind::{},", kw.name));
            let text_code = self.emit_string_literal(&kw.literal);
            self.line(&format!("text: {},", text_code));
            self.line(
                "span: Span { start, end: self.pos, line: start_line, column: start_column },",
            );
            self.indent -= 1;
            self.line("});");
            self.indent -= 1;
            self.line("}");
        }
        self.line("");
    }

    fn emit_literal_token_matching(&mut self) {
        // Collect and sort literal tokens by length (longest first)
        let mut literals: Vec<(&TokenDef, &str)> = self
            .grammar
            .lexer
            .tokens
            .iter()
            .filter_map(|t| match &t.kind {
                TokenKind::Literal(s) if !s.is_empty() => Some((t, s.as_str())),
                _ => None,
            })
            .collect();

        literals.sort_by(|a, b| b.1.len().cmp(&a.1.len()));

        if literals.is_empty() {
            return;
        }

        self.line("// Check literal tokens");
        for (token, literal) in literals {
            let escaped = literal.replace('\\', "\\\\").replace('"', "\\\"");
            self.line(&format!("if remaining.starts_with(\"{}\") {{", escaped));
            self.indent += 1;
            self.line(&format!("let len = {};", literal.len()));
            self.line("self.pos += len;");
            self.line("self.column += len;");
            self.line("return Ok(Token {");
            self.indent += 1;
            self.line(&format!("kind: TokenKind::{},", token.name));
            let text_code = self.emit_string_literal(literal);
            self.line(&format!("text: {},", text_code));
            self.line(
                "span: Span { start, end: self.pos, line: start_line, column: start_column },",
            );
            self.indent -= 1;
            self.line("});");
            self.indent -= 1;
            self.line("}");
        }
        self.line("");
    }

    fn emit_pattern_token_matching(&mut self) {
        let patterns: Vec<&TokenDef> = self
            .grammar
            .lexer
            .tokens
            .iter()
            .filter(|t| matches!(&t.kind, TokenKind::Pattern(_)))
            .collect();

        if patterns.is_empty() {
            return;
        }

        self.line("// Check pattern-based tokens");
        self.line("let c = remaining.chars().next().unwrap();");
        self.line("");

        for token in patterns {
            if let TokenKind::Pattern(pattern) = &token.kind {
                self.emit_pattern_check(token, pattern);
            }
        }
    }

    fn emit_pattern_check(&mut self, token: &TokenDef, pattern: &crate::ir::TokenPattern) {
        // Generate start condition check
        if let Some(ref start) = pattern.start {
            let start_cond = self.condition_to_rust(start, "c");
            self.line(&format!("if {} {{", start_cond));
            self.indent += 1;

            self.line("let mut end = self.pos + c.len_utf8();");

            // Generate continuation loop
            if let Some(ref cont) = pattern.continuation {
                let cont_cond = self.condition_to_rust(cont, "next_c");
                self.line(&format!(
                    "while end < self.input.len() && {{ let next_c = self.input[end..].chars().next().unwrap(); {} }} {{",
                    cont_cond
                ));
                self.indent += 1;
                self.line("end += self.input[end..].chars().next().unwrap().len_utf8();");
                self.indent -= 1;
                self.line("}");
            }

            // Handle special scanning modes
            if let Some(ref special) = pattern.special {
                self.emit_special_scan(special);
            }

            self.line("");
            let text_code = self.emit_string_from_slice("&self.input[self.pos..end]");
            self.line(&format!("let text = {};", text_code));
            self.line("let len = end - self.pos;");
            self.line("self.pos = end;");
            self.line("self.column += len;");
            self.line("return Ok(Token {");
            self.indent += 1;
            self.line(&format!("kind: TokenKind::{},", token.name));
            self.line("text,");
            self.line(
                "span: Span { start, end: self.pos, line: start_line, column: start_column },",
            );
            self.indent -= 1;
            self.line("});");

            self.indent -= 1;
            self.line("}");
            self.line("");
        }
    }

    fn emit_special_scan(&mut self, special: &SpecialScan) {
        match special {
            SpecialScan::UntilMatchingQuote => {
                self.line("// Scan until matching quote");
                self.line("let quote = c;");
                self.line("end = self.pos + 1;");
                self.line("while end < self.input.len() {");
                self.indent += 1;
                self.line("let ch = self.input[end..].chars().next().unwrap();");
                self.line("if ch == '\\\\' {");
                self.indent += 1;
                self.line("end += 2; // Skip escape");
                self.indent -= 1;
                self.line("} else if ch == quote {");
                self.indent += 1;
                self.line("end += 1; // Include closing quote");
                self.line("break;");
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("end += ch.len_utf8();");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            SpecialScan::TemplateHead => {
                self.line("// TODO: Scan template head");
            }
            SpecialScan::TemplateMiddle => {
                self.line("// TODO: Scan template middle");
            }
            SpecialScan::TemplateTail => {
                self.line("// TODO: Scan template tail");
            }
        }
    }

    fn condition_to_rust(&self, cond: &crate::ir::CharCondition, var: &str) -> String {
        use crate::ir::CharCondition;
        match cond {
            CharCondition::Class(name) => match name.as_str() {
                "digit" => format!("{}.is_ascii_digit()", var),
                "alpha" => format!("{}.is_ascii_alphabetic()", var),
                "alphanumeric" => format!("{}.is_ascii_alphanumeric()", var),
                "whitespace" => format!("{}.is_ascii_whitespace()", var),
                "hex" => format!("{}.is_ascii_hexdigit()", var),
                _ => format!("/* unknown class: {} */ false", name),
            },
            CharCondition::Char(c) => format!("{} == '{}'", var, escape_char(*c)),
            CharCondition::Range(from, to) => {
                format!(
                    "({} >= '{}' && {} <= '{}')",
                    var,
                    escape_char(*from),
                    var,
                    escape_char(*to)
                )
            }
            CharCondition::Any => "true".to_string(),
            CharCondition::Eof => format!("{} == '\\0'", var),
            CharCondition::Or(a, b) => {
                format!(
                    "({} || {})",
                    self.condition_to_rust(a, var),
                    self.condition_to_rust(b, var)
                )
            }
            CharCondition::And(a, b) => {
                format!(
                    "({} && {})",
                    self.condition_to_rust(a, var),
                    self.condition_to_rust(b, var)
                )
            }
            CharCondition::Not(a) => {
                format!("!({})", self.condition_to_rust(a, var))
            }
        }
    }

    fn emit_skip_whitespace(&mut self) {
        self.line("fn skip_whitespace(&mut self) {");
        self.indent += 1;
        self.line("while self.pos < self.input.len() {");
        self.indent += 1;
        self.line("let c = self.input[self.pos..].chars().next().unwrap();");
        self.line("if c == ' ' || c == '\\t' || c == '\\r' {");
        self.indent += 1;
        self.line("self.pos += 1;");
        self.line("self.column += 1;");
        self.indent -= 1;
        self.line("} else if c == '\\n' {");
        self.indent += 1;
        self.line("self.pos += 1;");
        self.line("self.line += 1;");
        self.line("self.column = 1;");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("break;");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_work_enum(&mut self) {
        self.line("/// Work items for trampoline execution");
        self.line("#[derive(Debug, Clone)]");
        self.line("pub enum Work {");
        self.indent += 1;

        // Generate Work variants for each rule
        for rule in &self.grammar.rules {
            self.emit_work_variants_for_rule(rule);
        }

        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn emit_work_variants_for_rule(&mut self, rule: &RuleDef) {
        let name = to_pascal_case(&rule.name);

        // Start variant
        self.line(&format!("{}_Start,", name));

        // Generate additional variants based on combinator type
        self.emit_work_variants_for_combinator(&name, &rule.combinator, 0);
    }

    fn emit_work_variants_for_combinator(&mut self, prefix: &str, comb: &Combinator, depth: usize) {
        match comb {
            Combinator::Sequence(items) => {
                // Skip step 0 - it's handled inline in the _Start variant
                for (i, item) in items.iter().enumerate().skip(1) {
                    // Each step needs to know which step it is and how many items to collect later
                    self.line(&format!(
                        "{}_Seq_Step{} {{ result_base: usize }},",
                        prefix, i
                    ));
                    // Recursively generate variants for nested complex combinators
                    let nested_prefix = format!("{}_Seq{}", prefix, i);
                    self.emit_work_variants_for_combinator(&nested_prefix, item, depth + 1);
                }
                // Also check first item for nested combinators
                if let Some(first) = items.first() {
                    let nested_prefix = format!("{}_Seq0", prefix);
                    self.emit_work_variants_for_combinator(&nested_prefix, first, depth + 1);
                }
                self.line(&format!(
                    "{}_Seq_Complete {{ result_base: usize, count: usize }},",
                    prefix
                ));
            }
            Combinator::Choice(items) => {
                for (i, item) in items.iter().enumerate() {
                    self.line(&format!(
                        "{}_Choice_Try{} {{ checkpoint: LexerCheckpoint, result_base: usize }},",
                        prefix, i
                    ));
                    // Recursively generate variants for nested complex combinators
                    let nested_prefix = format!("{}_Choice{}", prefix, i);
                    self.emit_work_variants_for_combinator(&nested_prefix, item, depth + 1);
                }
            }
            Combinator::ZeroOrMore(inner) | Combinator::OneOrMore(inner) => {
                self.line(&format!(
                    "{}_Repeat_Collect {{ result_base: usize, count: usize }},",
                    prefix
                ));
                // Recursively generate variants for the inner combinator
                let nested_prefix = format!("{}_Item", prefix);
                self.emit_work_variants_for_combinator(&nested_prefix, inner, depth + 1);
            }
            Combinator::Optional(inner) => {
                self.line(&format!(
                    "{}_Opt_Try {{ checkpoint: LexerCheckpoint, result_base: usize }},",
                    prefix
                ));
                // Recursively generate variants for the inner combinator
                let nested_prefix = format!("{}_OptInner", prefix);
                self.emit_work_variants_for_combinator(&nested_prefix, inner, depth + 1);
            }
            Combinator::Pratt(pratt_def) => {
                // Pratt_Start is not needed - Pratt parsing starts from the rule's _Start variant
                self.line(&format!(
                    "{}_Pratt_AfterOperand {{ min_prec: u8 }},",
                    prefix
                ));
                self.line(&format!(
                    "{}_Pratt_AfterRhs {{ min_prec: u8, op_token: Token }},",
                    prefix
                ));
                self.line(&format!(
                    "{}_Pratt_AfterPrefix {{ op_token: Token }},",
                    prefix
                ));
                // Complex postfix variants
                for op in &pratt_def.postfix_ops {
                    match op {
                        crate::ir::PostfixOp::Call { precedence, .. } => {
                            self.line(&format!(
                                "{}_Pratt_AfterCallArgs {{ min_prec: u8, prec: u8, result_base: usize }},",
                                prefix
                            ));
                            let _ = precedence;
                        }
                        crate::ir::PostfixOp::Index { precedence, .. } => {
                            self.line(&format!(
                                "{}_Pratt_AfterIndex {{ min_prec: u8, prec: u8 }},",
                                prefix
                            ));
                            let _ = precedence;
                        }
                        crate::ir::PostfixOp::Member { precedence, .. } => {
                            self.line(&format!(
                                "{}_Pratt_AfterMember {{ min_prec: u8, prec: u8, dot_token: Token }},",
                                prefix
                            ));
                            let _ = precedence;
                        }
                        crate::ir::PostfixOp::Simple { .. } => {} // Already handled
                    }
                }
                // Ternary operator variants
                if pratt_def.ternary.is_some() {
                    self.line(&format!(
                        "{}_Pratt_AfterTernaryThen {{ min_prec: u8, question_token: Token }},",
                        prefix
                    ));
                    self.line(&format!(
                        "{}_Pratt_AfterTernaryElse {{ min_prec: u8, question_token: Token, colon_token: Token }},",
                        prefix
                    ));
                }
            }
            Combinator::Mapped { inner, .. } => {
                self.emit_work_variants_for_combinator(prefix, inner, depth);
            }
            Combinator::SeparatedBy {
                item, separator, ..
            } => {
                self.line(&format!(
                    "{}_Sep_Collect {{ result_base: usize, count: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}_Sep_AfterItem {{ result_base: usize, count: usize }},",
                    prefix
                ));
                self.line(&format!(
                    "{}_Sep_AfterSep {{ result_base: usize, count: usize, checkpoint: LexerCheckpoint }},",
                    prefix
                ));
                // Recursively generate variants for item and separator
                let item_prefix = format!("{}_SepItem", prefix);
                self.emit_work_variants_for_combinator(&item_prefix, item, depth + 1);
                let sep_prefix = format!("{}_SepSep", prefix);
                self.emit_work_variants_for_combinator(&sep_prefix, separator, depth + 1);
            }
            Combinator::Skip(inner) => {
                let skip_prefix = format!("{}_Skip", prefix);
                self.emit_work_variants_for_combinator(&skip_prefix, inner, depth + 1);
            }
            Combinator::Lookahead(inner) => {
                let lookahead_prefix = format!("{}_Lookahead", prefix);
                self.emit_work_variants_for_combinator(&lookahead_prefix, inner, depth + 1);
            }
            Combinator::NegativeLookahead(inner) => {
                let neg_lookahead_prefix = format!("{}_NegLookahead", prefix);
                self.emit_work_variants_for_combinator(&neg_lookahead_prefix, inner, depth + 1);
            }
            _ => {}
        }
        let _ = depth; // Silence unused warning for now
    }

    fn emit_parse_result_enum(&mut self) {
        // Skip if configured to use external AST types
        if !self.grammar.ast_config.generate_parse_result {
            return;
        }

        self.line("/// Intermediate parse results");
        self.line("#[derive(Debug, Clone)]");
        self.line("pub enum ParseResult {");
        self.indent += 1;
        self.line("Token(Token),");
        self.line("None, // For optional that didn't match");
        self.line("List(Vec<ParseResult>), // For sequences, repetitions");

        // One variant per rule
        for rule in &self.grammar.rules {
            let name = to_pascal_case(&rule.name);
            self.line(&format!("{}(Box<ParseResult>),", name));
        }

        self.indent -= 1;
        self.line("}");
        self.line("");

        // Generate helper methods for ParseResult when apply_mappings is enabled
        if self.grammar.ast_config.apply_mappings {
            self.emit_parse_result_helpers();
        }
    }

    /// Generate helper methods for ParseResult extraction
    fn emit_parse_result_helpers(&mut self) {
        self.line("impl ParseResult {");
        self.indent += 1;

        // into_token()
        self.line("/// Extract the Token from a ParseResult::Token variant");
        self.line("#[allow(dead_code)]");
        self.line("pub fn into_token(self) -> Token {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        self.line("ParseResult::Token(t) => t,");
        self.line("_ => panic!(\"Expected Token, got {:?}\", self),");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // as_token()
        self.line("/// Get a reference to the Token from a ParseResult::Token variant");
        self.line("#[allow(dead_code)]");
        self.line("pub fn as_token(&self) -> &Token {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        self.line("ParseResult::Token(t) => t,");
        self.line("_ => panic!(\"Expected Token, got {:?}\", self),");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // into_list()
        self.line("/// Extract the Vec from a ParseResult::List variant");
        self.line("#[allow(dead_code)]");
        self.line("pub fn into_list(self) -> Vec<ParseResult> {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        self.line("ParseResult::List(v) => v,");
        self.line("_ => panic!(\"Expected List, got {:?}\", self),");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // as_list()
        self.line("/// Get a reference to the Vec from a ParseResult::List variant");
        self.line("#[allow(dead_code)]");
        self.line("pub fn as_list(&self) -> &Vec<ParseResult> {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        self.line("ParseResult::List(v) => v,");
        self.line("_ => panic!(\"Expected List, got {:?}\", self),");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // is_none()
        self.line("/// Check if this is ParseResult::None");
        self.line("#[allow(dead_code)]");
        self.line("pub fn is_none(&self) -> bool {");
        self.indent += 1;
        self.line("matches!(self, ParseResult::None)");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // into_option()
        self.line("/// Convert to Option, returning None if ParseResult::None");
        self.line("#[allow(dead_code)]");
        self.line("pub fn into_option(self) -> Option<ParseResult> {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        self.line("ParseResult::None => None,");
        self.line("other => Some(other),");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // span() helper
        self.line("/// Get the span of this parse result (from first token or default)");
        self.line("#[allow(dead_code)]");
        self.line("pub fn span(&self) -> Span {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        self.line("ParseResult::Token(t) => t.span,");
        self.line(
            "ParseResult::List(items) => items.first().map(|i| i.span()).unwrap_or_default(),",
        );
        self.line("ParseResult::None => Span::default(),");
        // Handle rule variants
        for rule in &self.grammar.rules {
            let name = to_pascal_case(&rule.name);
            self.line(&format!("ParseResult::{}(inner) => inner.span(),", name));
        }
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // combined_span() helper - calculates span from first to last element
        self.line("/// Get the combined span of this parse result (from first to last token)");
        self.line("#[allow(dead_code)]");
        self.line("pub fn combined_span(&self) -> Span {");
        self.indent += 1;
        self.line("match self {");
        self.indent += 1;
        self.line("ParseResult::Token(t) => t.span,");
        self.line("ParseResult::List(items) => {");
        self.indent += 1;
        self.line("if items.is_empty() {");
        self.indent += 1;
        self.line("return Span::default();");
        self.indent -= 1;
        self.line("}");
        self.line("let first = items.first().map(|i| i.combined_span()).unwrap_or_default();");
        self.line("let last = items.last().map(|i| i.combined_span()).unwrap_or_default();");
        self.line("first.merge(last)");
        self.indent -= 1;
        self.line("}");
        self.line("ParseResult::None => Span::default(),");
        // Handle rule variants
        for rule in &self.grammar.rules {
            let name = to_pascal_case(&rule.name);
            self.line(&format!(
                "ParseResult::{}(inner) => inner.combined_span(),",
                name
            ));
        }
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");

        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn emit_parser(&mut self) {
        // ParseError - skip if using external error type
        if self.grammar.ast_config.generate_parse_error {
            let span_type = self
                .grammar
                .ast_config
                .span_type
                .as_deref()
                .unwrap_or("Span");

            self.line("/// Parse error");
            self.line("#[derive(Debug, Clone)]");
            self.line("pub struct ParseError {");
            self.indent += 1;
            self.line(&format!("pub span: {},", span_type));
            self.line("pub expected: Vec<TokenKind>,");
            self.line("pub found: String,");
            self.indent -= 1;
            self.line("}");
            self.line("");

            self.line("impl std::fmt::Display for ParseError {");
            self.indent += 1;
            self.line("fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {");
            self.indent += 1;
            self.line("write!(f, \"{}:{}: expected {:?}, found {}\", self.span.line, self.span.column, self.expected, self.found)");
            self.indent -= 1;
            self.line("}");
            self.indent -= 1;
            self.line("}");
            self.line("");
            self.line("impl std::error::Error for ParseError {}");
            self.line("");
        }

        // Parser struct
        let has_string_dict = self.grammar.ast_config.string_dict_type.is_some();
        let string_dict_type = self
            .grammar
            .ast_config
            .string_dict_type
            .as_deref()
            .unwrap_or("StringDict");

        self.line("/// Parser with trampoline execution");
        self.line("pub struct Parser<'a> {");
        self.indent += 1;
        self.line("lexer: Lexer<'a>,");
        self.line("work_stack: Vec<Work>,");
        self.line("result_stack: Vec<ParseResult>,");
        self.line("last_error: Option<ParseError>,");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // Parser impl
        self.line("impl<'a> Parser<'a> {");
        self.indent += 1;

        if has_string_dict {
            self.line(&format!(
                "pub fn new(input: &'a str, string_dict: &'a mut {}) -> Self {{",
                string_dict_type
            ));
            self.indent += 1;
            self.line("Self {");
            self.indent += 1;
            self.line("lexer: Lexer::new(input, string_dict),");
        } else {
            self.line("pub fn new(input: &'a str) -> Self {");
            self.indent += 1;
            self.line("Self {");
            self.indent += 1;
            self.line("lexer: Lexer::new(input),");
        }
        self.line("work_stack: Vec::new(),");
        self.line("result_stack: Vec::new(),");
        self.line("last_error: None,");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");

        // Main parse function
        self.emit_parse_function();

        // execute_work
        self.emit_execute_work();

        // Helper to expect token
        self.emit_expect_token();

        self.indent -= 1;
        self.line("}");
    }

    fn emit_parse_function(&mut self) {
        self.line("pub fn parse(&mut self) -> Result<ParseResult, ParseError> {");
        self.indent += 1;

        if let Some(first_rule) = self.grammar.rules.first() {
            let name = to_pascal_case(&first_rule.name);
            self.line(&format!("self.work_stack.push(Work::{}_Start);", name));
        }

        self.line("");
        self.line("while let Some(work) = self.work_stack.pop() {");
        self.indent += 1;
        self.line("self.execute_work(work)?;");
        self.indent -= 1;
        self.line("}");
        self.line("");
        self.line("self.result_stack.pop().ok_or_else(|| ParseError {");
        self.indent += 1;
        self.line("span: self.lexer.span(),");
        self.line("expected: vec![],");
        self.line("found: \"no result\".to_string(),");
        self.indent -= 1;
        self.line("})");
        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn emit_execute_work(&mut self) {
        self.line("fn execute_work(&mut self, work: Work) -> Result<(), ParseError> {");
        self.indent += 1;
        self.line("match work {");
        self.indent += 1;

        // Generate match arms for each rule
        for rule in &self.grammar.rules {
            self.emit_rule_execution(rule);
        }

        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.line("");
    }

    fn emit_rule_execution(&mut self, rule: &RuleDef) {
        let name = to_pascal_case(&rule.name);

        // Start variant - begin parsing this rule
        self.line(&format!("Work::{}_Start => {{", name));
        self.indent += 1;
        self.emit_combinator_start(&name, &rule.combinator);
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");

        // Additional work variants for this rule's combinator
        self.emit_combinator_execution(&name, &rule.combinator);
    }

    fn emit_combinator_start(&mut self, prefix: &str, comb: &Combinator) {
        match comb {
            Combinator::Token(token_name) => {
                self.line(&format!(
                    "let token = self.expect_token(TokenKind::{})?;",
                    token_name
                ));
                self.line("self.result_stack.push(ParseResult::Token(token));");
            }
            Combinator::Rule(rule_name) => {
                let rule_pascal = to_pascal_case(rule_name);
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start);",
                    rule_pascal
                ));
            }
            Combinator::Sequence(items) => {
                if items.is_empty() {
                    self.line("self.result_stack.push(ParseResult::List(vec![]));");
                } else {
                    self.line("let result_base = self.result_stack.len();");
                    // Push completion work first (will be executed last)
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Seq_Complete {{ result_base, count: {} }});",
                        prefix,
                        items.len()
                    ));
                    // Push steps in reverse order
                    for i in (1..items.len()).rev() {
                        self.line(&format!(
                            "self.work_stack.push(Work::{}_Seq_Step{} {{ result_base }});",
                            prefix, i
                        ));
                    }
                    // Execute first item immediately
                    let first_prefix = format!("{}_Seq0", prefix);
                    self.emit_combinator_inline(&items[0], &first_prefix);
                }
            }
            Combinator::Choice(items) => {
                if items.is_empty() {
                    self.line("return Err(ParseError {");
                    self.indent += 1;
                    self.line("span: self.lexer.span(),");
                    self.line("expected: vec![],");
                    self.line("found: \"empty choice\".to_string(),");
                    self.indent -= 1;
                    self.line("});");
                } else {
                    self.line("let checkpoint = self.lexer.checkpoint();");
                    self.line("let result_base = self.result_stack.len();");
                    // Push first alternative, which will try others on failure
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Choice_Try0 {{ checkpoint, result_base }});",
                        prefix
                    ));
                }
            }
            Combinator::ZeroOrMore(inner) => {
                self.line("let result_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Repeat_Collect {{ result_base, count: 0 }});",
                    prefix
                ));
                let _ = inner;
            }
            Combinator::OneOrMore(inner) => {
                self.line("let result_base = self.result_stack.len();");
                // For one_or_more, we first parse one item, then switch to repeat mode
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Repeat_Collect {{ result_base, count: 0 }});",
                    prefix
                ));
                let _ = inner;
            }
            Combinator::Optional(inner) => {
                self.line("let checkpoint = self.lexer.checkpoint();");
                self.line("let result_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Opt_Try {{ checkpoint, result_base }});",
                    prefix
                ));
                let _ = inner;
            }
            Combinator::Pratt(pratt_def) => {
                // Check for prefix operators before parsing operand
                if !pratt_def.prefix_ops.is_empty() {
                    self.line("// Check for prefix operators");
                    self.line("let peek_token = self.lexer.peek()?;");
                    self.line(
                        "let (is_prefix, maybe_op_token, prefix_prec) = match peek_token.kind {",
                    );
                    self.indent += 1;
                    for op in &pratt_def.prefix_ops {
                        self.line(&format!(
                            "TokenKind::{} => (true, Some(self.lexer.next()?), {}u8),",
                            op.token, op.precedence
                        ));
                    }
                    self.line("_ => (false, None, 0u8),");
                    self.indent -= 1;
                    self.line("};");
                    self.line("");
                    self.line("if let Some(op_token) = maybe_op_token {");
                    self.indent += 1;
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Pratt_AfterPrefix {{ op_token }});",
                        prefix
                    ));
                    self.indent -= 1;
                    self.line("}");
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec: if is_prefix {{ prefix_prec }} else {{ 0 }} }});",
                        prefix
                    ));
                } else {
                    // No prefix operators - simple case
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec: 0 }});",
                        prefix
                    ));
                }
                // Parse operand
                if let Some(ref operand) = *pratt_def.operand {
                    let operand_prefix = format!("{}_Pratt_Operand", prefix);
                    self.emit_combinator_inline(operand, &operand_prefix);
                }
            }
            Combinator::Mapped { inner, mapping } => {
                // Parse the inner combinator first
                self.emit_combinator_start(prefix, inner);
                // When apply_mappings is enabled, generate mapping application code
                if self.grammar.ast_config.apply_mappings {
                    self.line(&format!("// AST Mapping: {}", mapping));
                    self.line("// The mapping closure above transforms the parsed result.");
                    self.line("// Use result_stack.pop() and apply the closure to get typed AST.");
                }
            }
            Combinator::Skip(inner) => {
                // Parse but discard
                let skip_prefix = format!("{}_Skip", prefix);
                self.emit_combinator_inline(inner, &skip_prefix);
                self.line("// Skip: result will be discarded");
            }
            Combinator::Lookahead(inner) => {
                // Positive lookahead: succeed if inner matches, but don't consume input
                self.line("let checkpoint = self.lexer.checkpoint();");
                self.line("let result_base = self.result_stack.len();");
                self.line("let try_result = (|| -> Result<(), ParseError> {");
                self.indent += 1;
                let lookahead_prefix = format!("{}_Lookahead", prefix);
                self.emit_combinator_inline(inner, &lookahead_prefix);
                self.line("Ok(())");
                self.indent -= 1;
                self.line("})();");
                self.line("// Always restore position");
                self.line("self.lexer.restore(checkpoint);");
                self.line("// Discard any results from the lookahead");
                self.line("while self.result_stack.len() > result_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line("// Propagate error or push None (lookahead produces no value)");
                self.line("try_result?;");
                self.line("self.result_stack.push(ParseResult::None);");
            }
            Combinator::NegativeLookahead(inner) => {
                // Negative lookahead: succeed if inner does NOT match
                self.line("let checkpoint = self.lexer.checkpoint();");
                self.line("let result_base = self.result_stack.len();");
                self.line("let try_result = (|| -> Result<(), ParseError> {");
                self.indent += 1;
                let lookahead_prefix = format!("{}_NegLookahead", prefix);
                self.emit_combinator_inline(inner, &lookahead_prefix);
                self.line("Ok(())");
                self.indent -= 1;
                self.line("})();");
                self.line("// Always restore position");
                self.line("self.lexer.restore(checkpoint);");
                self.line("// Discard any results from the lookahead");
                self.line("while self.result_stack.len() > result_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line("// For negative lookahead: succeed if inner failed");
                self.line("match try_result {");
                self.indent += 1;
                self.line("Ok(()) => {");
                self.indent += 1;
                self.line("// Inner succeeded, so negative lookahead fails");
                self.line("return Err(ParseError {");
                self.indent += 1;
                self.line(
                    "span: self.lexer.peek().map(|t| t.span).unwrap_or(Span { start: 0, end: 0 }),",
                );
                self.line("expected: vec![],");
                self.line("found: \"negative lookahead matched\".to_string(),");
                self.indent -= 1;
                self.line("});");
                self.indent -= 1;
                self.line("}");
                self.line("Err(_) => {");
                self.indent += 1;
                self.line("// Inner failed, so negative lookahead succeeds");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::SeparatedBy { item, .. } => {
                self.line("let result_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Sep_Collect {{ result_base, count: 0 }});",
                    prefix
                ));
                let _ = item;
            }
        }
    }

    fn emit_combinator_inline(&mut self, comb: &Combinator, prefix: &str) {
        match comb {
            Combinator::Token(token_name) => {
                self.line(&format!(
                    "let token = self.expect_token(TokenKind::{})?;",
                    token_name
                ));
                self.line("self.result_stack.push(ParseResult::Token(token));");
            }
            Combinator::Rule(rule_name) => {
                let rule_pascal = to_pascal_case(rule_name);
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Start);",
                    rule_pascal
                ));
            }
            Combinator::Mapped { inner, mapping } => {
                self.emit_combinator_inline(inner, prefix);
                // When apply_mappings is enabled, generate mapping application code
                if self.grammar.ast_config.apply_mappings {
                    self.line(&format!("// AST Mapping: {}", mapping));
                }
            }
            Combinator::Optional(_) => {
                self.line("let checkpoint = self.lexer.checkpoint();");
                self.line("let result_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Opt_Try {{ checkpoint, result_base }});",
                    prefix
                ));
            }
            Combinator::ZeroOrMore(_) | Combinator::OneOrMore(_) => {
                self.line("let result_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Repeat_Collect {{ result_base, count: 0 }});",
                    prefix
                ));
            }
            Combinator::Choice(_) => {
                self.line("let checkpoint = self.lexer.checkpoint();");
                self.line("let result_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Choice_Try0 {{ checkpoint, result_base }});",
                    prefix
                ));
            }
            Combinator::Sequence(items) => {
                if items.is_empty() {
                    self.line("self.result_stack.push(ParseResult::List(vec![]));");
                } else {
                    self.line("let result_base = self.result_stack.len();");
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Seq_Complete {{ result_base, count: {} }});",
                        prefix,
                        items.len()
                    ));
                    for i in (1..items.len()).rev() {
                        self.line(&format!(
                            "self.work_stack.push(Work::{}_Seq_Step{} {{ result_base }});",
                            prefix, i
                        ));
                    }
                    let first_prefix = format!("{}_Seq0", prefix);
                    self.emit_combinator_inline(&items[0], &first_prefix);
                }
            }
            Combinator::SeparatedBy { .. } => {
                self.line("let result_base = self.result_stack.len();");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Sep_Collect {{ result_base, count: 0 }});",
                    prefix
                ));
            }
            Combinator::Skip(inner) => {
                // Parse but discard the result
                let skip_prefix = format!("{}_Skip", prefix);
                self.emit_combinator_inline(inner, &skip_prefix);
                self.line("// Skip: result will be discarded");
            }
            Combinator::Lookahead(inner) => {
                // Positive lookahead: succeed if inner matches, but don't consume input
                self.line("let checkpoint = self.lexer.checkpoint();");
                self.line("let result_base = self.result_stack.len();");
                self.line("let try_result = (|| -> Result<(), ParseError> {");
                self.indent += 1;
                let lookahead_prefix = format!("{}_Lookahead", prefix);
                self.emit_combinator_inline(inner, &lookahead_prefix);
                self.line("Ok(())");
                self.indent -= 1;
                self.line("})();");
                self.line("// Always restore position");
                self.line("self.lexer.restore(checkpoint);");
                self.line("// Discard any results from the lookahead");
                self.line("while self.result_stack.len() > result_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line("// Propagate error or push None (lookahead produces no value)");
                self.line("try_result?;");
                self.line("self.result_stack.push(ParseResult::None);");
            }
            Combinator::NegativeLookahead(inner) => {
                // Negative lookahead: succeed if inner does NOT match
                self.line("let checkpoint = self.lexer.checkpoint();");
                self.line("let result_base = self.result_stack.len();");
                self.line("let try_result = (|| -> Result<(), ParseError> {");
                self.indent += 1;
                let neg_lookahead_prefix = format!("{}_NegLookahead", prefix);
                self.emit_combinator_inline(inner, &neg_lookahead_prefix);
                self.line("Ok(())");
                self.indent -= 1;
                self.line("})();");
                self.line("// Always restore position");
                self.line("self.lexer.restore(checkpoint);");
                self.line("// Discard any results from the lookahead");
                self.line("while self.result_stack.len() > result_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line("// For negative lookahead: succeed if inner failed");
                self.line("match try_result {");
                self.indent += 1;
                self.line("Ok(()) => {");
                self.indent += 1;
                self.line("// Inner succeeded, so negative lookahead fails");
                self.line("return Err(ParseError {");
                self.indent += 1;
                self.line("span: self.lexer.peek().map(|t| t.span).unwrap_or(Span { start: 0, end: 0, line: 0, column: 0 }),");
                self.line("expected: vec![],");
                self.line("found: \"negative lookahead matched\".to_string(),");
                self.indent -= 1;
                self.line("});");
                self.indent -= 1;
                self.line("}");
                self.line("Err(_) => {");
                self.indent += 1;
                self.line("// Inner failed, so negative lookahead succeeds");
                self.line("self.result_stack.push(ParseResult::None);");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::Pratt(pratt_def) => {
                // Start Pratt parsing - same as emit_combinator_start
                if !pratt_def.prefix_ops.is_empty() {
                    self.line("// Check for prefix operators");
                    self.line("let peek_token = self.lexer.peek()?;");
                    self.line(
                        "let (is_prefix, maybe_op_token, prefix_prec) = match peek_token.kind {",
                    );
                    self.indent += 1;
                    for op in &pratt_def.prefix_ops {
                        self.line(&format!(
                            "TokenKind::{} => (true, Some(self.lexer.next()?), {}u8),",
                            op.token, op.precedence
                        ));
                    }
                    self.line("_ => (false, None, 0u8),");
                    self.indent -= 1;
                    self.line("};");
                    self.line("");
                    self.line("if let Some(op_token) = maybe_op_token {");
                    self.indent += 1;
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Pratt_AfterPrefix {{ op_token }});",
                        prefix
                    ));
                    self.indent -= 1;
                    self.line("}");
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec: if is_prefix {{ prefix_prec }} else {{ 0 }} }});",
                        prefix
                    ));
                } else {
                    self.line(&format!(
                        "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec: 0 }});",
                        prefix
                    ));
                }
                if let Some(ref operand) = *pratt_def.operand {
                    let operand_prefix = format!("{}_Pratt_Operand", prefix);
                    self.emit_combinator_inline(operand, &operand_prefix);
                }
            }
        }
    }

    fn emit_combinator_execution(&mut self, prefix: &str, comb: &Combinator) {
        match comb {
            Combinator::Sequence(items) => {
                // Generate step handlers
                for (i, item) in items.iter().enumerate().skip(1) {
                    self.line(&format!(
                        "Work::{}_Seq_Step{} {{ result_base }} => {{",
                        prefix, i
                    ));
                    self.indent += 1;
                    let step_prefix = format!("{}_Seq{}", prefix, i);
                    self.emit_combinator_inline(item, &step_prefix);
                    self.line("Ok(())");
                    self.indent -= 1;
                    self.line("}");
                    // Generate execution handlers for nested combinators
                    self.emit_combinator_execution(&step_prefix, item);
                }
                // Also generate execution for first item if it's complex
                if let Some(first) = items.first() {
                    let first_prefix = format!("{}_Seq0", prefix);
                    self.emit_combinator_execution(&first_prefix, first);
                }
                // Complete handler - collect results
                self.line(&format!(
                    "Work::{}_Seq_Complete {{ result_base, count }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line(
                    "let results: Vec<_> = self.result_stack.drain(result_base..).collect();",
                );
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.line("Ok(())");
                self.indent -= 1;
                self.line("}");
            }
            Combinator::Choice(items) => {
                for (i, item) in items.iter().enumerate() {
                    self.line(&format!(
                        "Work::{}_Choice_Try{} {{ checkpoint, result_base }} => {{",
                        prefix, i
                    ));
                    self.indent += 1;
                    let alt_prefix = format!("{}_Choice{}", prefix, i);

                    // Try this alternative
                    self.line("let try_result = (|| -> Result<(), ParseError> {");
                    self.indent += 1;
                    self.emit_combinator_inline(item, &alt_prefix);
                    self.line("Ok(())");
                    self.indent -= 1;
                    self.line("})();");
                    self.line("");
                    self.line("match try_result {");
                    self.indent += 1;
                    self.line("Ok(()) => {");
                    self.indent += 1;
                    self.line("// Success - result is on stack");
                    self.line("Ok(())");
                    self.indent -= 1;
                    self.line("}");
                    self.line("Err(e) => {");
                    self.indent += 1;
                    self.line("// Restore and try next alternative");
                    self.line("self.lexer.restore(checkpoint.clone());");
                    self.line("while self.result_stack.len() > result_base {");
                    self.indent += 1;
                    self.line("self.result_stack.pop();");
                    self.indent -= 1;
                    self.line("}");

                    if i + 1 < items.len() {
                        self.line(&format!(
                            "self.work_stack.push(Work::{}_Choice_Try{} {{ checkpoint, result_base }});",
                            prefix,
                            i + 1
                        ));
                        self.line("Ok(())");
                    } else {
                        self.line("Err(e) // No more alternatives");
                    }

                    self.indent -= 1;
                    self.line("}");
                    self.indent -= 1;
                    self.line("}");

                    self.indent -= 1;
                    self.line("}");
                }
                // Generate execution handlers for nested combinators in each alternative
                for (i, item) in items.iter().enumerate() {
                    let alt_prefix = format!("{}_Choice{}", prefix, i);
                    self.emit_combinator_execution(&alt_prefix, item);
                }
            }
            Combinator::ZeroOrMore(inner) | Combinator::OneOrMore(inner) => {
                let item_prefix = format!("{}_Item", prefix);
                // Collect handler - try to parse another item (with error catching)
                self.line(&format!(
                    "Work::{}_Repeat_Collect {{ result_base, count }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let checkpoint = self.lexer.checkpoint();");
                self.line("let try_result = (|| -> Result<(), ParseError> {");
                self.indent += 1;
                self.emit_combinator_inline(inner, &item_prefix);
                self.line("Ok(())");
                self.indent -= 1;
                self.line("})();");
                self.line("");
                self.line("match try_result {");
                self.indent += 1;
                self.line("Ok(()) => {");
                self.indent += 1;
                self.line("// Item parsed, try for more");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Repeat_Collect {{ result_base, count: count + 1 }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("}");
                self.line("Err(_) => {");
                self.indent += 1;
                self.line("// Failed - restore lexer and collect successful items");
                self.line("self.lexer.restore(checkpoint);");
                self.line("// Discard any partial results from failed attempt (result_base + count are the successful ones)");
                self.line("while self.result_stack.len() > result_base + count {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line(
                    "let results: Vec<_> = self.result_stack.drain(result_base..).collect();",
                );
                self.line("self.result_stack.push(ParseResult::List(results));");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
                self.line("Ok(())");
                self.indent -= 1;
                self.line("}");
                // Generate execution handlers for nested combinators
                self.emit_combinator_execution(&item_prefix, inner);
            }
            Combinator::Optional(inner) => {
                let opt_inner_prefix = format!("{}_OptInner", prefix);
                self.line(&format!(
                    "Work::{}_Opt_Try {{ checkpoint, result_base }} => {{",
                    prefix
                ));
                self.indent += 1;
                self.line("let try_result = (|| -> Result<(), ParseError> {");
                self.indent += 1;
                self.emit_combinator_inline(inner, &opt_inner_prefix);
                self.line("Ok(())");
                self.indent -= 1;
                self.line("})();");
                self.line("");
                self.line("match try_result {");
                self.indent += 1;
                self.line("Ok(()) => Ok(()), // Result is on stack");
                self.line("Err(_) => {");
                self.indent += 1;
                self.line("self.lexer.restore(checkpoint);");
                self.line("while self.result_stack.len() > result_base {");
                self.indent += 1;
                self.line("self.result_stack.pop();");
                self.indent -= 1;
                self.line("}");
                self.line("self.result_stack.push(ParseResult::None);");
                self.line("Ok(())");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
                self.indent -= 1;
                self.line("}");
                // Generate execution handlers for nested combinators
                self.emit_combinator_execution(&opt_inner_prefix, inner);
            }
            Combinator::Pratt(pratt_def) => {
                self.emit_pratt_execution(prefix, pratt_def);
            }
            Combinator::Mapped { inner, mapping } => {
                self.emit_combinator_execution(prefix, inner);
                // Note: mapping is applied after inner combinator completes
                if self.grammar.ast_config.apply_mappings {
                    let _ = mapping; // Mapping string is available for code generation
                }
            }
            Combinator::SeparatedBy {
                item,
                separator,
                trailing,
            } => {
                self.emit_separated_by_execution(prefix, item, separator, *trailing);
            }
            _ => {}
        }
    }

    fn emit_pratt_execution(&mut self, prefix: &str, pratt_def: &crate::ir::PrattDef) {
        // Categorize postfix operators
        let simple_postfix_ops: Vec<_> = pratt_def
            .postfix_ops
            .iter()
            .filter_map(|op| {
                if let crate::ir::PostfixOp::Simple {
                    token, precedence, ..
                } = op
                {
                    Some((token.clone(), *precedence))
                } else {
                    None
                }
            })
            .collect();

        let call_ops: Vec<_> = pratt_def
            .postfix_ops
            .iter()
            .filter_map(|op| {
                if let crate::ir::PostfixOp::Call {
                    open,
                    close,
                    precedence,
                    ..
                } = op
                {
                    Some((open.clone(), close.clone(), *precedence))
                } else {
                    None
                }
            })
            .collect();

        let index_ops: Vec<_> = pratt_def
            .postfix_ops
            .iter()
            .filter_map(|op| {
                if let crate::ir::PostfixOp::Index {
                    open,
                    close,
                    precedence,
                    ..
                } = op
                {
                    Some((open.clone(), close.clone(), *precedence))
                } else {
                    None
                }
            })
            .collect();

        let member_ops: Vec<_> = pratt_def
            .postfix_ops
            .iter()
            .filter_map(|op| {
                if let crate::ir::PostfixOp::Member {
                    token, precedence, ..
                } = op
                {
                    Some((token.clone(), *precedence))
                } else {
                    None
                }
            })
            .collect();

        // AfterOperand - we have the left operand, now look for operators
        self.line(&format!(
            "Work::{}_Pratt_AfterOperand {{ min_prec }} => {{",
            prefix
        ));
        self.indent += 1;
        self.line("let token = self.lexer.peek()?;");

        // Generate unified operator precedence lookup
        // op_type: 0=none, 1=infix, 2=simple postfix, 3=call, 4=index, 5=member
        self.line("let (prec, assoc_right, op_type) = match token.kind {");
        self.indent += 1;

        // Infix operators (type 1)
        for op in &pratt_def.infix_ops {
            let assoc_val = if op.assoc == crate::Assoc::Right {
                "true"
            } else {
                "false"
            };
            self.line(&format!(
                "TokenKind::{} => ({}, {}, 1u8),",
                op.token, op.precedence, assoc_val
            ));
        }

        // Simple postfix operators (type 2)
        for (token, prec) in &simple_postfix_ops {
            self.line(&format!("TokenKind::{} => ({}, false, 2u8),", token, prec));
        }

        // Call postfix operators (type 3)
        for (open, _, prec) in &call_ops {
            self.line(&format!("TokenKind::{} => ({}, false, 3u8),", open, prec));
        }

        // Index postfix operators (type 4)
        for (open, _, prec) in &index_ops {
            self.line(&format!("TokenKind::{} => ({}, false, 4u8),", open, prec));
        }

        // Member postfix operators (type 5)
        for (token, prec) in &member_ops {
            self.line(&format!("TokenKind::{} => ({}, false, 5u8),", token, prec));
        }

        // Ternary operator (type 6)
        if let Some(ref ternary) = pratt_def.ternary {
            // Ternary is right-associative
            self.line(&format!(
                "TokenKind::{} => ({}, true, 6u8),",
                ternary.first_token, ternary.precedence
            ));
        }

        self.line("_ => (0, false, 0u8),");
        self.indent -= 1;
        self.line("};");
        self.line("");

        self.line("if prec > min_prec || (prec == min_prec && assoc_right) {");
        self.indent += 1;
        self.line("let _op_token = self.lexer.next()?;");
        self.line("match op_type {");
        self.indent += 1;

        // Infix operator (type 1)
        self.line("1 => {");
        self.indent += 1;
        self.line("// Infix operator");
        self.line("let next_min_prec = if assoc_right { prec } else { prec + 1 };");
        self.line(&format!(
            "self.work_stack.push(Work::{}_Pratt_AfterRhs {{ min_prec, op_token: _op_token }});",
            prefix
        ));
        self.line(&format!(
            "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec: next_min_prec }});",
            prefix
        ));
        // Parse RHS operand
        if let Some(ref operand) = *pratt_def.operand {
            let operand_prefix = format!("{}_Pratt_Operand", prefix);
            self.emit_combinator_inline(operand, &operand_prefix);
        }
        self.indent -= 1;
        self.line("}");

        // Simple postfix (type 2)
        self.line("2 => {");
        self.indent += 1;
        self.line("// Simple postfix operator");
        self.line("let operand = self.result_stack.pop().unwrap();");
        self.line(
            "self.result_stack.push(ParseResult::List(vec![operand, ParseResult::Token(_op_token)]));",
        );
        self.line(&format!(
            "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec }});",
            prefix
        ));
        self.indent -= 1;
        self.line("}");

        // Call postfix (type 3)
        if !call_ops.is_empty() {
            self.line("3 => {");
            self.indent += 1;
            self.line("// Call expression: callee(args)");
            self.line("let result_base = self.result_stack.len();");
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterCallArgs {{ min_prec, prec, result_base }});",
                prefix
            ));
            // Parse first argument (or nothing if empty)
            self.line("// Check if immediately closing");
            if let Some((_, close, _)) = call_ops.first() {
                self.line(&format!(
                    "if self.lexer.peek()?.kind != TokenKind::{} {{",
                    close
                ));
                self.indent += 1;
                // Parse first argument - it's a full expression
                self.line(&format!("self.work_stack.push(Work::{}_Start);", prefix));
                self.indent -= 1;
                self.line("}");
            }
            self.indent -= 1;
            self.line("}");
        }

        // Index postfix (type 4)
        if !index_ops.is_empty() {
            self.line("4 => {");
            self.indent += 1;
            self.line("// Index expression: obj[index]");
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterIndex {{ min_prec, prec }});",
                prefix
            ));
            // Parse index expression
            self.line(&format!("self.work_stack.push(Work::{}_Start);", prefix));
            self.indent -= 1;
            self.line("}");
        }

        // Member postfix (type 5)
        if !member_ops.is_empty() {
            self.line("5 => {");
            self.indent += 1;
            self.line("// Member access: obj.prop");
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterMember {{ min_prec, prec, dot_token: _op_token }});",
                prefix
            ));
            // Expect an identifier
            self.line("let prop_token = self.lexer.next()?;");
            self.line("self.result_stack.push(ParseResult::Token(prop_token));");
            self.indent -= 1;
            self.line("}");
        }

        // Ternary operator (type 6)
        if pratt_def.ternary.is_some() {
            self.line("6 => {");
            self.indent += 1;
            self.line("// Ternary: cond ? then : else");
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterTernaryThen {{ min_prec, question_token: _op_token }});",
                prefix
            ));
            // Parse 'then' expression at lowest precedence (allows any expression)
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec: 0 }});",
                prefix
            ));
            if let Some(ref operand) = *pratt_def.operand {
                let operand_prefix = format!("{}_Pratt_Operand", prefix);
                self.emit_combinator_inline(operand, &operand_prefix);
            }
            self.indent -= 1;
            self.line("}");
        }

        self.line("_ => {}");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("// No more operators at this precedence - done");
        self.indent -= 1;
        self.line("}");
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");

        // AfterRhs - combine left and right operands
        self.line(&format!(
            "Work::{}_Pratt_AfterRhs {{ min_prec, op_token }} => {{",
            prefix
        ));
        self.indent += 1;
        self.line("// Combine: left op right");
        self.line("let right = self.result_stack.pop().unwrap();");
        self.line("let left = self.result_stack.pop().unwrap();");
        self.line(
            "self.result_stack.push(ParseResult::List(vec![left, ParseResult::Token(op_token), right]));",
        );
        self.line("// Continue looking for more operators");
        self.line(&format!(
            "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec }});",
            prefix
        ));
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");

        // AfterPrefix - combine prefix operator with operand
        self.line(&format!(
            "Work::{}_Pratt_AfterPrefix {{ op_token }} => {{",
            prefix
        ));
        self.indent += 1;
        self.line("// Combine: prefix_op operand");
        self.line("let operand = self.result_stack.pop().unwrap();");
        self.line(
            "self.result_stack.push(ParseResult::List(vec![ParseResult::Token(op_token), operand]));",
        );
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");

        // AfterCallArgs - collect call arguments and combine
        if !call_ops.is_empty() {
            self.line(&format!(
                "Work::{}_Pratt_AfterCallArgs {{ min_prec, prec, result_base }} => {{",
                prefix
            ));
            self.indent += 1;
            self.line("let _ = prec;");
            self.line("// Check for closing paren or comma");
            self.line("let token = self.lexer.peek()?;");
            if let Some((_, close, _)) = call_ops.first() {
                self.line(&format!("if token.kind == TokenKind::{} {{", close));
                self.indent += 1;
                self.line("// Closing paren - collect args");
                self.line("self.lexer.next()?; // consume close");
                self.line("let args: Vec<_> = self.result_stack.drain(result_base..).collect();");
                self.line("let callee = self.result_stack.pop().unwrap();");
                self.line(
                    "self.result_stack.push(ParseResult::List(vec![callee, ParseResult::List(args)]));",
                );
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("} else if token.kind == TokenKind::COMMA {");
                self.indent += 1;
                self.line("// More args");
                self.line("self.lexer.next()?; // consume comma");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Pratt_AfterCallArgs {{ min_prec, prec, result_base }});",
                    prefix
                ));
                self.line(&format!("self.work_stack.push(Work::{}_Start);", prefix));
                self.indent -= 1;
                self.line("} else {");
                self.indent += 1;
                self.line("// Also accept closing paren without comma after last arg");
                self.line(&format!(
                    "self.work_stack.push(Work::{}_Pratt_AfterCallArgs {{ min_prec, prec, result_base }});",
                    prefix
                ));
                self.indent -= 1;
                self.line("}");
            }
            self.line("Ok(())");
            self.indent -= 1;
            self.line("}");
        }

        // AfterIndex - combine obj and index
        if !index_ops.is_empty() {
            self.line(&format!(
                "Work::{}_Pratt_AfterIndex {{ min_prec, prec }} => {{",
                prefix
            ));
            self.indent += 1;
            self.line("let _ = prec;");
            self.line("// Expect closing bracket");
            if let Some((_, close, _)) = index_ops.first() {
                self.line(&format!("self.expect_token(TokenKind::{})?;", close));
            }
            self.line("let index = self.result_stack.pop().unwrap();");
            self.line("let obj = self.result_stack.pop().unwrap();");
            self.line("self.result_stack.push(ParseResult::List(vec![obj, index]));");
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec }});",
                prefix
            ));
            self.line("Ok(())");
            self.indent -= 1;
            self.line("}");
        }

        // AfterMember - combine obj and property
        if !member_ops.is_empty() {
            self.line(&format!(
                "Work::{}_Pratt_AfterMember {{ min_prec, prec, dot_token }} => {{",
                prefix
            ));
            self.indent += 1;
            self.line("let _ = prec;");
            self.line("let prop = self.result_stack.pop().unwrap();");
            self.line("let obj = self.result_stack.pop().unwrap();");
            self.line(
                "self.result_stack.push(ParseResult::List(vec![obj, ParseResult::Token(dot_token), prop]));",
            );
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec }});",
                prefix
            ));
            self.line("Ok(())");
            self.indent -= 1;
            self.line("}");
        }

        // AfterTernaryThen - we have 'then', now parse ':' and 'else'
        if let Some(ref ternary) = pratt_def.ternary {
            self.line(&format!(
                "Work::{}_Pratt_AfterTernaryThen {{ min_prec, question_token }} => {{",
                prefix
            ));
            self.indent += 1;
            self.line("// Expect colon");
            self.line(&format!(
                "let colon_token = self.expect_token(TokenKind::{})?;",
                ternary.second_token
            ));
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterTernaryElse {{ min_prec, question_token, colon_token }});",
                prefix
            ));
            // Parse 'else' expression at ternary precedence (right-associative)
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec: {} }});",
                prefix, ternary.precedence
            ));
            if let Some(ref operand) = *pratt_def.operand {
                let operand_prefix = format!("{}_Pratt_Operand", prefix);
                self.emit_combinator_inline(operand, &operand_prefix);
            }
            self.line("Ok(())");
            self.indent -= 1;
            self.line("}");

            // AfterTernaryElse - combine cond, then, else
            self.line(&format!(
                "Work::{}_Pratt_AfterTernaryElse {{ min_prec, question_token, colon_token }} => {{",
                prefix
            ));
            self.indent += 1;
            self.line("// Combine: cond ? then : else");
            self.line("let else_expr = self.result_stack.pop().unwrap();");
            self.line("let then_expr = self.result_stack.pop().unwrap();");
            self.line("let cond_expr = self.result_stack.pop().unwrap();");
            self.line("self.result_stack.push(ParseResult::List(vec![");
            self.indent += 1;
            self.line("cond_expr,");
            self.line("ParseResult::Token(question_token),");
            self.line("then_expr,");
            self.line("ParseResult::Token(colon_token),");
            self.line("else_expr,");
            self.indent -= 1;
            self.line("]));");
            self.line(&format!(
                "self.work_stack.push(Work::{}_Pratt_AfterOperand {{ min_prec }});",
                prefix
            ));
            self.line("Ok(())");
            self.indent -= 1;
            self.line("}");
        }
    }

    fn emit_separated_by_execution(
        &mut self,
        prefix: &str,
        item: &Combinator,
        separator: &Combinator,
        _trailing: bool,
    ) {
        let item_prefix = format!("{}_SepItem", prefix);
        let sep_prefix = format!("{}_SepSep", prefix);

        // Collect - try to parse first/next item
        self.line(&format!(
            "Work::{}_Sep_Collect {{ result_base, count }} => {{",
            prefix
        ));
        self.indent += 1;
        self.line(&format!(
            "self.work_stack.push(Work::{}_Sep_AfterItem {{ result_base, count }});",
            prefix
        ));
        self.emit_combinator_inline(item, &item_prefix);
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");

        // AfterItem - check if item succeeded, then look for separator
        self.line(&format!(
            "Work::{}_Sep_AfterItem {{ result_base, count }} => {{",
            prefix
        ));
        self.indent += 1;
        self.line("if self.result_stack.len() > result_base + count {");
        self.indent += 1;
        self.line("// Item succeeded, look for separator");
        self.line("let checkpoint = self.lexer.checkpoint();");
        self.line(&format!(
            "self.work_stack.push(Work::{}_Sep_AfterSep {{ result_base, count: count + 1, checkpoint }});",
            prefix
        ));
        self.emit_combinator_inline(separator, &sep_prefix);
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("// Item failed - collect results");
        self.line("let results: Vec<_> = self.result_stack.drain(result_base..).collect();");
        self.line("self.result_stack.push(ParseResult::List(results));");
        self.indent -= 1;
        self.line("}");
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");

        // AfterSep - separator found, parse next item
        self.line(&format!(
            "Work::{}_Sep_AfterSep {{ result_base, count, checkpoint }} => {{",
            prefix
        ));
        self.indent += 1;
        self.line("// Separator matched, try next item");
        self.line("// Pop separator result (we don't keep it)");
        self.line("self.result_stack.pop();");
        self.line(&format!(
            "self.work_stack.push(Work::{}_Sep_Collect {{ result_base, count }});",
            prefix
        ));
        self.line("let _ = checkpoint; // TODO: handle trailing separator");
        self.line("Ok(())");
        self.indent -= 1;
        self.line("}");

        // Generate execution handlers for nested item and separator combinators
        self.emit_combinator_execution(&item_prefix, item);
        self.emit_combinator_execution(&sep_prefix, separator);
    }

    fn emit_expect_token(&mut self) {
        self.line("fn expect_token(&mut self, expected: TokenKind) -> Result<Token, ParseError> {");
        self.indent += 1;
        self.line("let token = self.lexer.next()?;");
        self.line("if token.kind == expected {");
        self.indent += 1;
        self.line("Ok(token)");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("Err(ParseError {");
        self.indent += 1;
        self.line("span: token.span,");
        self.line("expected: vec![expected],");
        self.line("found: format!(\"{:?}\", token.kind),");
        self.indent -= 1;
        self.line("})");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
    }

    fn line(&mut self, text: &str) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
        self.output.push_str(text);
        self.output.push('\n');
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().chain(chars).collect(),
                None => String::new(),
            }
        })
        .collect()
}

fn escape_char(c: char) -> String {
    match c {
        '\'' => "\\'".to_string(),
        '\\' => "\\\\".to_string(),
        '\n' => "\\n".to_string(),
        '\r' => "\\r".to_string(),
        '\t' => "\\t".to_string(),
        _ => c.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use crate::Grammar;

    #[test]
    fn test_generate_simple() {
        let grammar = Grammar::new()
            .lexer(|l| l.token("PLUS", "+").token("NUMBER", ""))
            .rule("expr", |r| r.token("NUMBER"))
            .build();

        let code = grammar.generate();
        assert!(code.contains("pub enum TokenKind"));
        assert!(code.contains("PLUS,"));
        assert!(code.contains("NUMBER,"));
        assert!(code.contains("pub enum Work"));
        assert!(code.contains("pub struct Parser"));
    }
}
