//! Generated parser for TypeScript.
//!
//! This module includes the parser generated at build time from the grammar definition.
//! The actual parser code is generated by build.rs and included from OUT_DIR.

// Allow warnings in generated code
// Note: clippy::indexing_slicing is explicitly allowed because the generated parser
// uses compile-time constant indices that are always valid
#![allow(
    dead_code,
    unused_variables,
    unused_mut,
    clippy::all,
    clippy::indexing_slicing
)]

include!(concat!(env!("OUT_DIR"), "/parser_generated.rs"));
