//! Generated parser for TypeScript.
//!
//! This module includes the parser generated at build time from the grammar definition.
//! The actual parser code is generated by build.rs and included from OUT_DIR.

// Allow warnings in generated code
#![allow(dead_code, unused_variables, clippy::all)]

include!(concat!(env!("OUT_DIR"), "/parser_generated.rs"));
